'use client';

import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, Bookmark, Check, ChefHat, ChevronDown, Clock3, Compass, Flame, Heart, House, Leaf, LogOut, Menu, Minus, MoreHorizontal, Pause, Play, Plus, Printer, Refrigerator, RotateCcw, Search, Settings, Share2, ShoppingBasket, Sparkles, Timer, Users, UserRound, WandSparkles, X, Bell, ExternalLink, SlidersHorizontal, CircleHelp, Pencil, CalendarDays } from 'lucide-react';
import type { Recipe } from './recipe-data';
import { getPreparationSteps } from './recipe-preparation';
import { getRecipeNutrition } from './nutrition-estimates';
import recipeInfoStyles from './RecipeInfo.module.css';
import type { User } from '@supabase/supabase-js';
import { createClient as createSupabaseClient, isSupabaseConfigured } from '../lib/supabase/client';

type Page = 'Home' | 'Generate' | 'Discover' | 'Recipe Search' | 'Recipe' | 'My Recipes' | 'Favorites' | 'My Kitchen' | 'Settings';
type PantryIngredient = { id:string; name:string; qty:string; unit:string; have:boolean };
type PantryItem = { id:string; name:string; quantity:number; unit:string; purchase_date:string|null; expiry_date:string|null; category:string; storage_type:string|null };
type SearchRecipe = { id:string; title:string; source:string; url:string; snippet:string; image:string; cuisine:string; category:string };
const units=['g','kg','ml','L','cups','tbsp','tsp','pieces','cloves','slices','handfuls','custom'];
const suggestions=['Avocado','Basil','Bell pepper','Broccoli','Carrot','Cauliflower','Chicken','Chickpeas','Cilantro','Coconut milk','Cucumber','Eggs','Garlic','Ginger','Lemon','Lentils','Mango','Mushrooms','Onion','Paneer','Peas','Potato','Rice','Salmon','Spinach','Tomato','Tofu','Yogurt','Zucchini'];
const cuisines=['Indian','North Indian','South Indian','Italian','Mexican','Chinese','Thai','Korean','Mediterranean','American','Fusion'];
const diets=['Vegetarian','Vegan','Eggless','Gluten-Free','Dairy-Free','High-Protein','Low-Calorie','Jain-friendly'];
const imageUrl=(id:string,w=900)=>id.startsWith('http')||id.startsWith('/')?id:`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
// Keep each recipe's own image as the only image layer. A shared fallback made
// failed image requests look like every recipe had the same photo.
const recipeImage=(r:Recipe,w=700)=>({backgroundImage:`url("${imageUrl(r.image,w)}")`,backgroundColor:'#e9e7dc'});

export default function FridgeChef() {
  const router=useRouter();
  const [page,setPage]=useState<Page>('Home');
  const [ingredients,setIngredients]=useState<PantryIngredient[]>([{id:'1',name:'',qty:'',unit:'pieces',have:true}]);
  const [servings,setServings]=useState(2),[cuisine,setCuisine]=useState('Indian'),[preferences,setPreferences]=useState<string[]>(['Vegetarian']);
  const [recipe,setRecipe]=useState<Recipe|null>(null),[recipeSource,setRecipeSource]=useState<'AI Generated'|'Discover'|'Search'|'Kitchen'>('AI Generated');
  const [saved,setSaved]=useState<Recipe[]>([]),[favorites,setFavorites]=useState<string[]>([]),[favoriteRecipes,setFavoriteRecipes]=useState<Recipe[]>([]),[inventory,setInventory]=useState<PantryItem[]>([]);
  const [user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(false),[accountOpen,setAccountOpen]=useState(false);
  const [recentlyViewed,setRecentlyViewed]=useState<Recipe[]>([]);
  const [featuredRecipes,setFeaturedRecipes]=useState<Recipe[]>([]);
  const [kitchenSuggestions,setKitchenSuggestions]=useState<Recipe[]>([]);
  const [catalogRecipes,setCatalogRecipes]=useState<Recipe[]>([]);
  const [catalogPage,setCatalogPage]=useState(1),[catalogTotal,setCatalogTotal]=useState(0),[catalogTotalPages,setCatalogTotalPages]=useState(0);
  const [catalogLoading,setCatalogLoading]=useState(false),[catalogError,setCatalogError]=useState('');
  const [loading,setLoading]=useState(false),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('All');
  const [generateError,setGenerateError]=useState('');
  const [localDemoMode,setLocalDemoMode]=useState(false);
  const [notifications,setNotifications]=useState<{id:number;title:string;message:string;read:boolean}[]>([]),[noticeOpen,setNoticeOpen]=useState(false),[mobileOpen,setMobileOpen]=useState(false);
  const [cookMode,setCookMode]=useState(false),[activeStep,setActiveStep]=useState(0),[seconds,setSeconds]=useState(0),[timerRunning,setTimerRunning]=useState(false);
  const noticeRef=useRef<HTMLDivElement>(null);
  const generationInFlight=useRef(false);
  useEffect(()=>{setLocalDemoMode(document.body.dataset.localDemoMode==='true')},[]);
  async function loadAccountData(userId:string){
    try{const supabase=createSupabaseClient();const [savedRows,favoriteRows,pantryRows,profileRow,recentRows]=await Promise.all([
      supabase.from('saved_recipes').select('recipe').eq('user_id',userId).order('created_at',{ascending:false}),
      supabase.from('favorites').select('recipe_id,recipe').eq('user_id',userId).order('created_at',{ascending:false}),
      supabase.from('pantry_items').select('id,name,quantity,unit,purchase_date,expiry_date,category,storage_type').eq('user_id',userId).order('expiry_date',{ascending:true,nullsFirst:false}),
      supabase.from('profiles').select('default_servings,favorite_cuisine,dietary_preferences').eq('id',userId).maybeSingle(),
      supabase.from('recently_viewed').select('recipe').eq('user_id',userId).order('viewed_at',{ascending:false}).limit(5),
    ]);if(savedRows.error||favoriteRows.error||pantryRows.error||profileRow.error||recentRows.error)throw savedRows.error||favoriteRows.error||pantryRows.error||profileRow.error||recentRows.error;
      setSaved((savedRows.data||[]).map(row=>row.recipe as Recipe));setFavoriteRecipes((favoriteRows.data||[]).map(row=>row.recipe as Recipe));setFavorites((favoriteRows.data||[]).map(row=>row.recipe_id));setInventory((pantryRows.data||[]) as PantryItem[]);
      setRecentlyViewed((recentRows.data||[]).map(row=>row.recipe as Recipe));
      if(profileRow.data){setServings(profileRow.data.default_servings||2);setCuisine(profileRow.data.favorite_cuisine||'Indian');setPreferences(profileRow.data.dietary_preferences||[])}
    }catch{notify('Your account data could not be loaded. Check the Supabase tables and try refreshing.')}
  }
  useEffect(()=>{
    if(!isSupabaseConfigured()){setAuthReady(true);return}
    let alive=true;const supabase=createSupabaseClient();
    const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{const activeUser=session?.user||null;if(!alive)return;setUser(activeUser);setAuthReady(true);if(activeUser)window.setTimeout(()=>{if(alive)void loadAccountData(activeUser.id)},0);else{setSaved([]);setFavorites([]);setFavoriteRecipes([]);setInventory([]);setRecentlyViewed([])}});
    void supabase.auth.getSession().then(({data})=>{if(alive&&data.session?.user){setUser(data.session.user);setAuthReady(true);void loadAccountData(data.session.user.id)}else if(alive)setAuthReady(true)});
    return()=>{alive=false;subscription.unsubscribe()}
  },[]);
  useEffect(()=>{const click=(e:MouseEvent)=>{if(noticeRef.current&&!noticeRef.current.contains(e.target as Node))setNoticeOpen(false)};document.addEventListener('mousedown',click);return()=>document.removeEventListener('mousedown',click)},[]);
  useEffect(()=>{if(!timerRunning)return;const id=window.setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>window.clearInterval(id)},[timerRunning]);
  useEffect(()=>{if(seconds===0)setTimerRunning(false)},[seconds]);
  useEffect(()=>{let active=true;fetch('/api/recipes/catalog?page=1&pageSize=4').then(async response=>{const data=await response.json();if(!response.ok)throw new Error('Catalog unavailable');if(active)setFeaturedRecipes(data.recipes||[])}).catch(()=>{if(active)setFeaturedRecipes([])});return()=>{active=false}},[]);
  useEffect(()=>{
    if(page!=='Discover')return;
    const controller=new AbortController();
    const params=new URLSearchParams({page:String(catalogPage),pageSize:'24',search,filter});
    const timer=window.setTimeout(()=>{
      setCatalogLoading(true);setCatalogError('');
      fetch(`/api/recipes/catalog?${params}`,{signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'The recipe collection could not be loaded.');setCatalogRecipes(data.recipes||[]);setCatalogTotal(data.total||0);setCatalogTotalPages(data.totalPages||0)}).catch(error=>{if(error instanceof DOMException&&error.name==='AbortError')return;setCatalogRecipes([]);setCatalogError(error instanceof Error?error.message:'The recipe collection could not be loaded. Please try again.')}).finally(()=>{if(!controller.signal.aborted)setCatalogLoading(false)});
    },140);
    return()=>{window.clearTimeout(timer);controller.abort()}
  },[page,search,filter,catalogPage]);
  useEffect(()=>{
    if(page!=='My Kitchen')return;
    const ingredients=inventory.filter(item=>{const days=expiryDays(item.expiry_date);return days!==null&&days>=0&&days<=5}).map(item=>item.name);
    if(!ingredients.length){setKitchenSuggestions([]);return}
    const params=new URLSearchParams({page:'1',pageSize:'3',ingredients:ingredients.join(',')});
    let active=true;fetch(`/api/recipes/catalog?${params}`).then(async response=>{const data=await response.json();if(response.ok&&active)setKitchenSuggestions(data.recipes||[])}).catch(()=>{if(active)setKitchenSuggestions([])});
    return()=>{active=false}
  },[page,inventory]);
  function notify(message:string){setToast(message);window.setTimeout(()=>setToast(''),2600)}
  function addNotification(title:string,message:string){setNotifications(n=>[{id:Date.now(),title,message,read:false},...n].slice(0,8))}
  function navigate(next:Page){if(['My Kitchen','Favorites','My Recipes'].includes(next)&&!user){requireLogin();return}setPage(next);setMobileOpen(false);setCookMode(false)}
  const displayName=String(user?.user_metadata?.full_name||user?.email?.split('@')[0]||'');
  const initials=(displayName||'G').trim().split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()).join('');
  function requireLogin(){if(user)return true;notify('Log in to keep recipes and pantry items in your account');router.push('/login?next=%2F');return false}
  async function logout(){if(!isSupabaseConfigured())return;const {error}=await createSupabaseClient().auth.signOut();if(error){notify('Unable to log out. Please try again.');return}setAccountOpen(false);notify('You have been logged out')}
  function startNewRecipe(){setIngredients([{id:String(Date.now()),name:'',qty:'',unit:'pieces',have:true}]);setRecipe(null);setServings(2);setCuisine('Indian');setPreferences(['Vegetarian']);setActiveStep(0);setSeconds(0);setTimerRunning(false);setCookMode(false);setPage('Generate')}
  function addIngredient(){setIngredients(v=>[...v,{id:String(Date.now()+Math.random()),name:'',qty:'',unit:'pieces',have:true}])}
  function updateIngredient(id:string,key:keyof PantryIngredient,value:string|boolean){setIngredients(v=>v.map(x=>x.id===id?{...x,[key]:value}:x))}
  function togglePreference(value:string){setPreferences(v=>v.includes(value)?v.filter(x=>x!==value):[...v,value])}
async function generateRecipe(){
    if(loading||generationInFlight.current)return;
    if(!ingredients.some(x=>x.name.trim())){notify('Add at least one ingredient to get started');return}
    generationInFlight.current=true;setLoading(true);setGenerateError('');
    try{
      const response=await fetch('/api/recipes/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ingredients:ingredients.filter(x=>x.name.trim()).map(x=>({name:x.name,quantity:x.qty,unit:x.unit,have:x.have})),servings,cuisine,preferences})});
      const contentType=response.headers.get('content-type')||'';
      const responseText=await response.text();
      const isJson=contentType.toLowerCase().includes('application/json')||contentType.toLowerCase().includes('+json');
      let payload:Record<string,any>|null=null;
      if(isJson){try{payload=JSON.parse(responseText) as Record<string,any>}catch{payload=null}}
      if(!isJson||!payload){
        if(process.env.NODE_ENV==='development'){
          const preview=responseText.replace(/sk-[A-Za-z0-9_-]{8,}/g,'[redacted]').slice(0,240);
          console.warn('Recipe generation returned a non-JSON response',{status:response.status,contentType,preview});
        }
        const message=response.status===404?'The recipe generation endpoint was not found. Restart FridgeChef from the project folder and try again.':response.status>=500?'The recipe service returned an unexpected server response. Check the development server output and try again.':'The recipe service returned an unexpected response. Please try again.';
        throw new Error(message);
      }
      if(!response.ok)throw new Error(typeof payload.error==='string'?payload.error:'We couldn’t generate a recipe just now. Please try again.');
      const data=payload.recipe;
      const ingredientDetails=data?.ingredients as NonNullable<Recipe['ingredientDetails']>|undefined;
      if(!data?.title||!Array.isArray(ingredientDetails)||!Array.isArray(data.steps))throw new Error('The recipe response was incomplete. Please try again.');
      type StructuredStep={stepNumber:number;title:string;description:string;duration:string|number;ingredients?:string[];ingredientsUsed?:string[];tip?:string};
      const rawSteps=data.steps as unknown[];
      const structuredSteps:StructuredStep[]=rawSteps.filter((step):step is StructuredStep=>!!step&&typeof step==='object'&&'description'in step&&'title'in step);
      const steps=rawSteps.map(step=>typeof step==='string'?step:step&&typeof step==='object'&&'description'in step?String(step.description):'').filter(Boolean);
      const preparationSteps=structuredSteps.length===rawSteps.length?structuredSteps.map((step:StructuredStep,index)=>({stepNumber:index+1,title:step.title,description:step.description,durationMinutes:typeof step.duration==='number'?step.duration:Number(String(step.duration).match(/\d+/)?.[0]||0),ingredients:Array.isArray(step.ingredients)?step.ingredients:Array.isArray(step.ingredientsUsed)?step.ingredientsUsed:[],tip:typeof step.tip==='string'?step.tip:undefined})):undefined;
      const names=ingredients.filter(x=>x.name.trim()).map(x=>x.name).join(' ');
      const prepMinutes=data.prepMinutes??data.prepTime;
      const cookMinutes=data.cookMinutes??data.cookTime;
      const next:Recipe={id:`generated-${Date.now()}`,title:data.title,cuisine:data.cuisine||cuisine,category:data.category||'Dinner',mealType:data.mealType||data.category||'Dinner',description:data.description||'A fresh recipe made around your ingredients.',image:/chicken|fish|salmon|egg|mutton/i.test(names)?'photo-1603360946369-dc9bb6258143':'photo-1547592180-85f173990554',minutes:data.minutes??(Number(prepMinutes||0)+Number(cookMinutes||0)),prepMinutes,cookMinutes,servings:payload.servings||servings,difficulty:data.difficulty==='Medium'?'Medium':'Easy',tags:Array.isArray(data.tags)?data.tags:[],ingredients:ingredientDetails.map(x=>x.name),ingredientDetails,steps,preparationSteps,tips:Array.isArray(data.tips)?data.tips:[],nutrition:data.nutrition||null,allergens:Array.isArray(data.allergens)?data.allergens.filter((value:unknown):value is string=>typeof value==='string'):[],servingSuggestions:Array.isArray(data.servingSuggestions)?data.servingSuggestions.filter((value:unknown):value is string=>typeof value==='string'):[],substitutions:Array.isArray(data.substitutions)?data.substitutions.filter((value:unknown)=>!!value&&typeof value==='object'&&typeof (value as {ingredient?:unknown}).ingredient==='string'&&typeof (value as {substitute?:unknown}).substitute==='string'):[]};
      setRecipe(next);setRecipeSource('AI Generated');setPage('Recipe');setActiveStep(0);addNotification('New recipe generated',next.title);notify('Your recipe is ready')
    }catch(error){const message=error instanceof Error?error.message:'We couldn’t generate a recipe just now. Please try again.';setGenerateError(message);notify('Recipe generation needs attention')}
    finally{generationInFlight.current=false;setLoading(false)}
  }
  async function saveRecipe(item=recipe){if(!item||!requireLogin())return;const exists=saved.some(x=>x.id===item.id);const supabase=createSupabaseClient();const result=exists?await supabase.from('saved_recipes').delete().eq('user_id',user!.id).eq('recipe_id',item.id):await supabase.from('saved_recipes').upsert({user_id:user!.id,recipe_id:item.id,recipe:item},{onConflict:'user_id,recipe_id'});if(result.error){notify('Unable to update saved recipes. Check your Supabase tables.');return}setSaved(v=>exists?v.filter(x=>x.id!==item.id):[item,...v]);notify(exists?'Removed from My Recipes':'Recipe saved');if(!exists)addNotification('Recipe saved',item.title)}
  async function toggleFavorite(item:Recipe){if(!requireLogin())return;const exists=favorites.includes(item.id);const supabase=createSupabaseClient();const result=exists?await supabase.from('favorites').delete().eq('user_id',user!.id).eq('recipe_id',item.id):await supabase.from('favorites').upsert({user_id:user!.id,recipe_id:item.id,recipe:item},{onConflict:'user_id,recipe_id'});if(result.error){notify('Unable to update favorites. Check your Supabase tables.');return}setFavorites(v=>exists?v.filter(x=>x!==item.id):[item.id,...v]);setFavoriteRecipes(v=>exists?v.filter(x=>x.id!==item.id):[item,...v]);notify(exists?'Removed from favorites':'Added to favorites')}
  async function persistPantryItem(item:Omit<PantryItem,'id'>&{id?:string}):Promise<boolean>{if(!requireLogin())return false;const supabase=createSupabaseClient();const values={...item,user_id:user!.id};const result=item.id?await supabase.from('pantry_items').update(values).eq('user_id',user!.id).eq('id',item.id):await supabase.from('pantry_items').insert(values);if(result.error){notify('Unable to save this pantry item. Check your Supabase tables.');return false}await loadAccountData(user!.id);notify(item.id?'Pantry item updated':'Pantry item added');return true}
  async function deletePantryItem(id:string){if(!requireLogin())return;const {error}=await createSupabaseClient().from('pantry_items').delete().eq('user_id',user!.id).eq('id',id);if(error){notify('Unable to remove this pantry item.');return}setInventory(v=>v.filter(x=>x.id!==id));notify('Pantry item removed')}
  async function deleteSavedRecipe(id:string){if(!requireLogin())return;const {error}=await createSupabaseClient().from('saved_recipes').delete().eq('user_id',user!.id).eq('recipe_id',id);if(error){notify('Unable to remove this recipe.');return}setSaved(v=>v.filter(r=>r.id!==id));notify('Recipe removed')}
  async function saveCookingPreferences(next:{default_servings:number;favorite_cuisine:string;dietary_preferences:string[]}){setServings(next.default_servings);setCuisine(next.favorite_cuisine);setPreferences(next.dietary_preferences);if(!user)return;const {error}=await createSupabaseClient().from('profiles').upsert({id:user.id,full_name:displayName,...next});if(error)notify('Unable to save profile preferences. Check your Supabase tables.');else notify('Cooking preferences saved')}
  function openRecipe(item:Recipe,source:'Discover'|'Search'|'Kitchen'='Discover'){setRecipe(item);setRecipeSource(source);setServings(item.servings);setRecentlyViewed(v=>[item,...v.filter(x=>x.id!==item.id)].slice(0,5));if(user)void createSupabaseClient().from('recently_viewed').upsert({user_id:user.id,recipe_id:item.id,recipe:item,viewed_at:new Date().toISOString()},{onConflict:'user_id,recipe_id'});setPage('Recipe');setActiveStep(0)}
  function finishCooking(){setCookMode(false);setActiveStep(0);addNotification('Cooking session completed',recipe?.title||'Your recipe');notify('Recipe complete — lovely work!')}

  if(cookMode&&recipe)return <CookMode recipe={recipe} servings={servings} step={activeStep} setStep={setActiveStep} seconds={seconds} setSeconds={setSeconds} running={timerRunning} setRunning={setTimerRunning} onFinish={finishCooking} onExit={()=>setCookMode(false)}/>;

  const nav: [Page,React.ReactNode][]=[['Home',<House key="h" size={17}/>],['Discover',<Compass key="d" size={17}/>],['Generate',<WandSparkles key="g" size={17}/>],['Recipe Search',<Search key="s" size={17}/>],['My Kitchen',<Refrigerator key="k" size={17}/>],['Favorites',<Heart key="f" size={17}/>],['My Recipes',<Bookmark key="b" size={17}/>]];

  return <div className="app-shell">
    <aside className="sidebar">
      <button className="brand" onClick={()=>navigate('Home')}><span className="brand-mark"><ChefHat size={21}/></span><span className="brand-name">fridge<span>chef</span><small>GOOD FOOD STARTS HERE</small></span></button>
      <div className="nav-label">YOUR KITCHEN</div><nav>{nav.map(([name,icon])=><button key={name} className={`nav-item ${page===name?'active':''}`} onClick={()=>navigate(name)}>{icon}<span>{name}</span>{name==='My Recipes'&&saved.length>0&&<small className="nav-count">{saved.length}</small>}</button>)}</nav>
      <div className="side-promo"><div className="promo-icon"><Leaf size={17}/></div><b>A little less waste.<br/>A lot more delicious.</b><p>Make something lovely with what you already have.</p><button onClick={()=>navigate('My Kitchen')}>Open my kitchen <ArrowRight size={13}/></button></div>
      <div className="profile-area"><button className="profile" onClick={()=>user?setAccountOpen(v=>!v):router.push('/login')} aria-expanded={accountOpen}><span className="avatar">{user?initials:<UserRound size={17}/>}</span><span><b>{user?displayName:'Log in'}</b><small>{user?.email||'Your account'}</small></span>{user?<Settings size={15}/>:<ArrowRight size={15}/>}</button>{accountOpen&&user&&<div className="account-popover"><b>{user.email}</b><button onClick={()=>{setAccountOpen(false);navigate('Settings')}}><Settings size={14}/> Cooking preferences</button><button onClick={()=>void logout()}><LogOut size={14}/> Log out</button></div>}</div>
    </aside>
    <main className="main-column">
      <header className="topbar"><div className="breadcrumb">{page==='Home'?<b>Good food starts here</b>:<><button onClick={()=>navigate('Home')}>Home</button><span>/</span><b>{page}</b></>}</div><div className="top-actions"><span className="inspiration">✳ &nbsp;A little inspiration for today</span><div className="notification-wrap" ref={noticeRef}><button className="icon-button" aria-label="Notifications" aria-expanded={noticeOpen} onClick={()=>setNoticeOpen(v=>!v)}><Bell size={18}/>{notifications.some(n=>!n.read)&&<i/>}</button>{noticeOpen&&<div className="notification-popover"><div className="notification-head"><b>Notifications</b><button onClick={()=>setNotifications(n=>n.map(x=>({...x,read:true})))}>Mark all as read</button></div>{notifications.length?notifications.map(n=><button className={`notification-item ${n.read?'read':''}`} key={n.id} onClick={()=>setNotifications(v=>v.map(x=>x.id===n.id?{...x,read:true}:x))}><Sparkles size={15}/><span><b>{n.title}</b><small>{n.message}</small></span>{!n.read&&<i/>}</button>):<p className="notification-empty">Your cooking updates will show up here.</p>}</div>}</div><button className="avatar small-avatar" aria-label={user?`Open ${displayName} account`:'Log in'} onClick={()=>user?navigate('Settings'):router.push('/login')}>{user?initials:<UserRound size={15}/>}</button></div></header>
      <button className="mobile-menu-toggle" aria-label="Open navigation" onClick={()=>setMobileOpen(v=>!v)}><Menu size={20}/><span>FridgeChef</span></button>
      {mobileOpen&&<nav className="mobile-menu">{nav.map(([n,icon])=><button key={n} onClick={()=>navigate(n)}>{icon}{n}</button>)}<button onClick={()=>navigate('Settings')}><Settings size={17}/>Settings</button></nav>}
      <AnimatePresence mode="wait"><motion.div key={page} className="page-content" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} transition={{duration:.18}}>
        {page==='Home'&&<HomePage featuredRecipes={featuredRecipes} onGenerate={()=>navigate('Generate')} onDiscover={()=>navigate('Discover')} onSearch={()=>navigate('Recipe Search')} onOpen={(r:Recipe)=>openRecipe(r,'Discover')} onSave={toggleFavorite} userName={user?displayName:''} expiring={inventory.filter(item=>{const days=expiryDays(item.expiry_date);return days!==null&&days>=0&&days<=5})} favorites={favoriteRecipes} recentlyViewed={recentlyViewed} onKitchen={()=>navigate('My Kitchen')} onFavorites={()=>navigate('Favorites')}/>}
        {page==='Generate'&&<GeneratePage ingredients={ingredients} update={updateIngredient} add={addIngredient} remove={(id:string)=>setIngredients(v=>v.filter(x=>x.id!==id))} servings={servings} setServings={setServings} cuisine={cuisine} setCuisine={setCuisine} preferences={preferences} togglePreference={togglePreference} loading={loading} error={generateError} generate={generateRecipe} localDemoMode={localDemoMode}/>}
        {page==='Discover'&&<DiscoverPage items={catalogRecipes} search={search} setSearch={value=>{setSearch(value);setCatalogPage(1)}} filter={filter} setFilter={value=>{setFilter(value);setCatalogPage(1)}} loading={catalogLoading} error={catalogError} total={catalogTotal} currentPage={catalogPage} totalPages={catalogTotalPages} setPage={setCatalogPage} onOpen={(r:Recipe)=>openRecipe(r,'Discover')} favorites={favorites} toggleFavorite={toggleFavorite} onGenerate={()=>navigate('Generate')}/>}
        {page==='Recipe Search'&&<SearchPage onOpen={(r:Recipe)=>openRecipe(r,'Search')}/>}
        {page==='Recipe'&&recipe&&<RecipePage recipe={recipe} servings={servings} setServings={setServings} fridgeIngredients={inventory.map(item=>item.name)} saved={saved.some(x=>x.id===recipe.id)} onSave={()=>saveRecipe(recipe)} onUpdate={setRecipe} onCook={()=>{setCookMode(true);setActiveStep(0)}} onBack={()=>navigate(recipeSource==='Search'?'Recipe Search':recipeSource==='Discover'?'Discover':recipeSource==='Kitchen'?'My Kitchen':'Generate')}/>}
        {page==='My Recipes'&&<LibraryPage recipes={saved} onOpen={(r:Recipe)=>openRecipe(r,'Discover')} onDelete={(id:string)=>void deleteSavedRecipe(id)} onGenerate={()=>startNewRecipe()}/>}
        {page==='Favorites'&&<LibraryPage title="Your favorites." subtitle="Recipes you’ve hearted for another day." recipes={favoriteRecipes} onOpen={(r:Recipe)=>openRecipe(r,'Discover')} onDelete={(id:string)=>{const item=favoriteRecipes.find(r=>r.id===id);if(item)void toggleFavorite(item)}} onGenerate={()=>startNewRecipe()}/>}
        {page==='My Kitchen'&&<KitchenPage items={inventory} suggestions={kitchenSuggestions} onSave={persistPantryItem} onDelete={deletePantryItem} onOpen={(r:Recipe)=>openRecipe(r,'Kitchen')} onFavorite={toggleFavorite} onGenerate={()=>{const usable=inventory.filter(item=>!item.expiry_date||(expiryDays(item.expiry_date)??-1)>=0);if(!usable.length){notify('Add fresh pantry items before generating a recipe');return}setIngredients(usable.map(item=>({id:item.id,name:item.name,qty:String(item.quantity),unit:item.unit,have:true})));navigate('Generate')}}/>}
        {page==='Settings'&&<SettingsPage servings={servings} setServings={setServings} cuisine={cuisine} setCuisine={setCuisine} preferences={preferences} togglePreference={togglePreference} onSave={saveCookingPreferences} user={user}/>}
      </motion.div></AnimatePresence>
      {toast&&<div className="toast" role="status"><Check size={15}/>{toast}</div>}
      <nav className="mobile-bottom-nav">{(['Home','Discover','Generate','My Recipes'] as Page[]).map((n,i)=><button key={n} className={`${page===n?'selected':''} ${n==='Generate'?'central':''}`} onClick={()=>n==='Generate'?startNewRecipe():navigate(n)}>{i===0?<House size={18}/>:i===1?<Compass size={18}/>:i===2?<Plus size={22}/>:<Bookmark size={18}/>}<span>{n==='My Recipes'?'Saved':n}</span></button>)}</nav>
    </main>
  </div>;
}

function HomePage({featuredRecipes,onGenerate,onDiscover,onSearch,onOpen,onSave,userName,expiring,favorites,recentlyViewed,onKitchen,onFavorites}:{featuredRecipes:Recipe[];onGenerate:()=>void;onDiscover:()=>void;onSearch:()=>void;onOpen:(r:Recipe)=>void;onSave:(r:Recipe)=>void;userName:string;expiring:PantryItem[];favorites:Recipe[];recentlyViewed:Recipe[];onKitchen:()=>void;onFavorites:()=>void}){
  const [quick,setQuick]=useState('');const [chips,setChips]=useState<string[]>(['Rice','Tomato','Onion']);
  function addChip(){const clean=quick.trim();if(clean&&!chips.some(c=>c.toLowerCase()===clean.toLowerCase()))setChips(v=>[...v,clean]);setQuick('')}
  return <>
    {userName&&<section className="dashboard-panel"><div className="dashboard-welcome"><div><div className="eyebrow muted">YOUR FRIDGECHEF DASHBOARD</div><h1>Welcome, <em>{userName}.</em></h1><p>Here’s something good to cook today.</p></div><button className="primary-button" onClick={onGenerate}><Sparkles size={15}/> Generate a recipe</button></div><div className="dashboard-tiles"><button onClick={onDiscover}><Compass size={16}/><b>Today's suggestions</b><small>Find a new dish to love</small></button><button onClick={onKitchen}><CalendarDays size={16}/><b>{expiring.length} expiring soon</b><small>{expiring[0]?.name?`Use ${expiring[0].name} soon`:'Keep your pantry fresh'}</small></button><button onClick={onFavorites}><Heart size={16}/><b>{favorites.length} favorites</b><small>Your saved inspiration</small></button></div>{recentlyViewed.length>0&&<div className="dashboard-recent"><b>Recently viewed</b>{recentlyViewed.slice(0,3).map(item=><button key={item.id} onClick={()=>onOpen(item)}>{item.title}<ArrowRight size={12}/></button>)}</div>}</section>}
    <section className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> A RECIPE, MADE AROUND YOU</div><h1>Turn your ingredients into something <em>delicious.</em></h1><p className="hero-sub">Tell FridgeChef what you have. We’ll help you figure out what to cook — one lovely meal at a time.</p><div className="hero-actions"><button className="primary-button" onClick={onGenerate}>Create my recipe <ArrowRight size={16}/></button><button className="text-button" onClick={onSearch}><Search size={15}/> Search recipes</button></div><div className="trust-row"><span><Sparkles size={14}/> AI recipes</span><span><SlidersHorizontal size={14}/> Smart quantities</span><span><Play size={13}/> Visual cooking</span></div></div><div className="hero-photo" style={{backgroundImage:`linear-gradient(180deg,#00000008 20%,#111b168a 100%),url("${imageUrl('photo-1547592180-85f173990554',1100)}"),url("${imageUrl('photo-1512621776951-a57141f2eefd',1100)}")`}}><div className="hero-photo-badge"><span className="live-dot"/> YOUR NEXT FAVORITE</div><div className="hero-photo-caption"><span>Fresh from your kitchen</span><b>Golden, cozy,<br/>made for you.</b></div></div></section>
    <section className="quick-builder"><div className="builder-head"><span className="builder-icon"><Refrigerator size={19}/></span><div><h2>What’s in your kitchen?</h2><p>Add a few ingredients to get a recipe idea.</p></div><button className="text-button builder-link" onClick={onGenerate}>Open full generator <ArrowRight size={14}/></button></div><div className="chip-entry"><div className="quick-chips">{chips.map((c,i)=><span className="ingredient-chip" key={`${c}-${i}`}>{c}<button aria-label={`Remove ${c}`} onClick={()=>setChips(v=>v.filter((_,idx)=>idx!==i))}><X size={12}/></button></span>)}<input aria-label="Add ingredient" placeholder="Add an ingredient…" value={quick} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(e.preventDefault(),addChip())}/></div><button className="primary-button compact-button" onClick={()=>{if(quick.trim())addChip();else onGenerate()}}>Make me something <ArrowRight size={14}/></button></div></section>
    <section className="section-block"><div className="section-heading"><div><div className="eyebrow muted">A LITTLE INSPIRATION</div><h2>What can I cook?</h2><p>Ideas for whatever kind of day it is.</p></div><button className="text-button" onClick={onDiscover}>Explore all <ArrowRight size={14}/></button></div><div className="recipe-grid home-recipes">{featuredRecipes.map((r,i)=><RecipeCard key={r.id} recipe={r} index={i} onOpen={()=>onOpen(r)} saved={favorites.some(item=>item.id===r.id)} onSave={()=>onSave(r)}/>)}</div></section>
    <section className="workflow"><div><div className="eyebrow muted">FIVE LITTLE STEPS</div><h2>From fridge to <em>favorite.</em></h2><p>Simple steps, big dinner energy.</p></div><div className="workflow-list">{[['🥕','Your ingredients'],['✳','AI analysis'],['🍲','Recipe'],['◉','Visual guide'],['♨','Cook mode']].map(([icon,label],i)=><div className="workflow-item" key={label}><span>{icon}</span><b>{label}</b>{i<4&&<ArrowRight size={14}/>}</div>)}</div></section>
  </>;
}

function GeneratePage({ingredients,update,add,remove,servings,setServings,cuisine,setCuisine,preferences,togglePreference,loading,error,generate,localDemoMode}:{ingredients:PantryIngredient[];update:(id:string,key:keyof PantryIngredient,value:string|boolean)=>void;add:()=>void;remove:(id:string)=>void;servings:number;setServings:(n:number)=>void;cuisine:string;setCuisine:(s:string)=>void;preferences:string[];togglePreference:(s:string)=>void;loading:boolean;error:string;generate:()=>void;localDemoMode:boolean}){
  const list=[...new Set(suggestions)];
  return <section className="generate-page"><PageIntro eyebrow="A RECIPE, MADE AROUND YOU" title={<>Let’s make <em>dinner.</em></>} sub="Your ingredients do the talking. We’ll take it from here." step="01"/>
    <div className="generator-layout"><div className="generator-main"><div className="form-card"><div className="form-card-heading"><span className="form-icon"><Refrigerator size={19}/></span><div><h2>What do you have?</h2><p>Add a few things from your fridge or pantry.</p></div><span className="step-badge">STEP 01</span></div><div className="ingredient-table-head"><span>INGREDIENT</span><span>QUANTITY</span><span>UNIT</span><span>IN YOUR KITCHEN</span><i/></div><div className="ingredient-rows">{ingredients.map(x=><div className="ingredient-row" key={x.id}><input aria-label="Ingredient name" list="ingredient-suggestions" value={x.name} onChange={e=>update(x.id,'name',e.target.value)} placeholder="e.g. spinach"/><input aria-label={`Quantity for ${x.name||'ingredient'}`} type="number" min="0" value={x.qty} onChange={e=>update(x.id,'qty',e.target.value)} placeholder="2"/><select aria-label={`Unit for ${x.name||'ingredient'}`} value={x.unit} onChange={e=>update(x.id,'unit',e.target.value)}>{units.map(u=><option key={u}>{u}</option>)}</select><label className="availability"><input type="checkbox" checked={x.have} onChange={e=>update(x.id,'have',e.target.checked)}/><span>{x.have?'Have it':'Need it'}</span></label><button className="row-remove" aria-label={`Remove ${x.name||'ingredient'}`} onClick={()=>remove(x.id)}><MoreHorizontal size={18}/></button></div>)}</div><datalist id="ingredient-suggestions">{list.map(i=><option key={i} value={i}/>)}</datalist><div className="ingredient-foot"><button className="outline-button" onClick={add}><Plus size={15}/> Add ingredient</button><span><CircleHelp size={14}/> We can estimate missing quantities for you.</span></div></div>
    <div className="form-card preference-card"><div className="form-card-heading"><span className="form-icon orange-icon"><SlidersHorizontal size={18}/></span><div><h2>Make it yours</h2><p>A few preferences help us get closer.</p></div><span className="step-badge">STEP 02</span></div><div className="preferences-grid"><label>Servings<div className="servings-control"><button onClick={()=>setServings(Math.max(1,servings-1))} aria-label="Decrease servings"><Minus size={13}/></button><b>{servings}</b><button onClick={()=>setServings(Math.min(12,servings+1))} aria-label="Increase servings"><Plus size={13}/></button></div></label><label>Cuisine<select value={cuisine} onChange={e=>setCuisine(e.target.value)}>{cuisines.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="preference-label">DIETARY PREFERENCES <small>Select all that apply</small></div><div className="diet-chips">{diets.map(d=><button key={d} onClick={()=>togglePreference(d)} className={preferences.includes(d)?'chosen':''}>{preferences.includes(d)&&<Check size={12}/>} {d}</button>)}</div></div>
    {localDemoMode&&<div className="demo-mode-label" role="status"><Sparkles size={13}/> Free Demo Mode <span>Runs without OpenAI API credits.</span></div>}<button className="primary-button generate-button" disabled={loading} onClick={generate}>{loading?<><span className="spinner"/> Finding your dinner…</>:<><Sparkles size={16}/> Generate recipe <ArrowRight size={16}/></>}</button>{error&&<p className="generate-error" role="alert">{error}</p>}</div><aside className="generator-aside"><div className="aside-photo" style={{backgroundImage:`url("${imageUrl('photo-1547592180-85f173990554',800)}"),url("${imageUrl('photo-1512621776951-a57141f2eefd',800)}")`}}/><h3>Good food, less guesswork.</h3><p>We’ll prioritize the ingredients you have, adjust amounts to your servings, and make each step easy to follow.</p><div className="aside-fact"><Check size={15}/> Flexible ingredient swaps</div><div className="aside-fact"><Check size={15}/> Servings that scale</div><div className="aside-fact"><Check size={15}/> Step-by-step Cook Mode</div></aside></div>
  </section>;
}

function PageIntro({eyebrow,title,sub,step}:{eyebrow:string;title:React.ReactNode;sub:string;step?:string}){return <div className="page-intro"><div><div className="eyebrow muted">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{step&&<span className="step-badge">STEP {step}</span>}</div>}

function DiscoverPage({items,search,setSearch,filter,setFilter,loading,error,total,currentPage,totalPages,setPage,onOpen,favorites,toggleFavorite,onGenerate}:{items:Recipe[];search:string;setSearch:(x:string)=>void;filter:string;setFilter:(x:string)=>void;loading:boolean;error:string;total:number;currentPage:number;totalPages:number;setPage:(n:number)=>void;onOpen:(r:Recipe)=>void;favorites:string[];toggleFavorite:(r:Recipe)=>void;onGenerate:()=>void}){
  const filters=['All','Indian','Quick','High protein','One pan','Vegetarian','Italian','Mexican','Asian','Mediterranean','American'];
  return <section><div className="page-intro"><div><div className="eyebrow muted">GOOD THINGS TO COOK</div><h1>Find your next <em>favorite.</em></h1><p>Browse dishes for whatever kind of day it is.</p></div><button className="outline-button" onClick={onGenerate}><SlidersHorizontal size={15}/> Use my ingredients</button></div><div className="discover-search"><Search size={18}/><input aria-label="Search recipes" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search recipes, ingredients, cuisines…"/><span>{total} ideas</span></div><div className="filter-tabs">{filters.map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div>{loading?<div className="recipe-grid discover-grid" aria-label="Loading recipes">{[0,1,2,3,4,5].map(i=><div className="search-skeleton" key={i}/>)}</div>:error?<div className="search-status error-status" role="alert"><p>{error}</p><button className="outline-button" onClick={()=>setPage(currentPage)}>Try again <RotateCcw size={14}/></button></div>:items.length?<><div className="recipe-grid discover-grid">{items.map((r,i)=><RecipeCard key={r.id} recipe={r} index={i} onOpen={()=>onOpen(r)} saved={favorites.includes(r.id)} onSave={()=>toggleFavorite(r)}/>)}</div>{totalPages>1&&<div className="catalog-pagination" aria-label="Recipe pages"><button className="outline-button" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}><ArrowLeft size={14}/> Previous</button><span>Page {currentPage} of {totalPages}</span><button className="outline-button" disabled={currentPage>=totalPages} onClick={()=>setPage(currentPage+1)}>Next <ArrowRight size={14}/></button></div>}</>:<EmptyState title="No recipes found" sub="Try a different ingredient or filter." action="Clear filters" onClick={()=>{setSearch('');setFilter('All')}}/>}</section>;
}

function RecipeCard({recipe,index,onOpen,onSave,saved}:{recipe:Recipe;index:number;onOpen:()=>void;onSave:()=>void;saved:boolean}){return <motion.article className="recipe-card" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:Math.min(index*.035,.24)}}><button className="recipe-image" style={recipeImage(recipe)} onClick={onOpen} aria-label={`View ${recipe.title}`}><span className="recipe-tag">{recipe.cuisine}</span><span className="recipe-time"><Clock3 size={12}/>{recipe.minutes} min</span></button><div className="recipe-card-body"><div className="recipe-card-top"><span>{recipe.category}</span><button className={`heart-button ${saved?'liked':''}`} onClick={onSave} aria-label={saved?'Remove favorite':'Add favorite'}><Heart size={17} fill={saved?'currentColor':'none'}/></button></div><button className="recipe-title" onClick={onOpen}>{recipe.title}</button><p>{recipe.description}</p><div className="recipe-card-foot"><span><Users size={13}/>{recipe.servings} servings</span><button onClick={onOpen}>View recipe <ArrowRight size={14}/></button></div></div></motion.article>}

function RecipePage({recipe,servings,setServings,fridgeIngredients,saved,onSave,onCook,onBack,onUpdate}:{recipe:Recipe;servings:number;setServings:(n:number)=>void;fridgeIngredients:string[];saved:boolean;onSave:()=>void;onCook:()=>void;onBack:()=>void;onUpdate:(r:Recipe)=>void}){
  const [detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState(''),[expanded,setExpanded]=useState<number|null>(null);
  useEffect(()=>{
    if(recipe.ingredientDetails?.length&&recipe.preparationSteps?.length)return;
    let active=true;setDetailLoading(true);setDetailError('');
    fetch('/api/recipes/enrich',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:recipe.title,cuisine:recipe.cuisine,category:recipe.category,description:recipe.description,ingredients:recipe.ingredients,servings:recipe.servings})})
      .then(async response=>{
        const data=await response.json();
        if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'Detailed guidance is unavailable.');
        if(!active)return;
        const rawSteps=Array.isArray(data.steps)?data.steps:[];
        if(!Array.isArray(data.ingredientDetails)||!data.ingredientDetails.length)throw new Error('Ingredient details are unavailable for this recipe.');
        const ingredientDetails:NonNullable<Recipe['ingredientDetails']>=(data.ingredientDetails as NonNullable<Recipe['ingredientDetails']>).map((item:{name:string;quantity:number|null;unit:string;substitution:string|null})=>{
          const prior=recipe.ingredientDetails?.find(existing=>existing.name.toLocaleLowerCase()===item.name.toLocaleLowerCase());
          return {...prior,...item,quantity:item.quantity??prior?.quantity??null,unit:item.unit||prior?.unit||'',substitution:item.substitution||prior?.substitution||null};
        });
        const preparationSteps=rawSteps.length&&rawSteps.every((step:unknown)=>!!step&&typeof step==='object'&&'title'in step&&'description'in step)
          ?rawSteps.map((step:{title:string;description:string;duration:number|string;ingredients?:string[];ingredientsUsed?:string[];tip?:string},index:number)=>({stepNumber:index+1,title:step.title,description:step.description,durationMinutes:typeof step.duration==='number'?step.duration:Number(String(step.duration).match(/\d+/)?.[0]||1),ingredients:Array.isArray(step.ingredients)?step.ingredients:Array.isArray(step.ingredientsUsed)?step.ingredientsUsed:[],tip:step.tip||undefined}))
          :undefined;
        const legacySteps=rawSteps.map((step:unknown)=>typeof step==='string'?step:step&&typeof step==='object'&&'description'in step?String((step as {description:unknown}).description):'').filter(Boolean);
        onUpdate({...recipe,ingredientDetails,ingredients:ingredientDetails.map(x=>x.name),steps:legacySteps,preparationSteps,tips:data.tips,nutrition:data.nutrition,prepMinutes:data.prepMinutes,cookMinutes:data.cookMinutes,minutes:(data.prepMinutes||0)+(data.cookMinutes||0)||recipe.minutes});
      })
      .catch(error=>{if(active)setDetailError(error instanceof Error?error.message:'Detailed cooking guidance is unavailable. This recipe is still ready to cook.')})
      .finally(()=>{if(active)setDetailLoading(false)});
    return()=>{active=false};
  },[recipe.id]);
  const nutrition=getRecipeNutrition(recipe);
  const preparationSteps=getPreparationSteps(recipe);
  const prep=recipe.prepMinutes??Math.max(5,Math.round(recipe.minutes*.25));const cook=recipe.cookMinutes??Math.max(0,recipe.minutes-prep);
  return <section className="recipe-detail"><button className="back-link" onClick={onBack}><ArrowLeft size={15}/> Back</button><div className="recipe-hero"><div className="recipe-hero-image" style={recipeImage(recipe,1200)} role="img" aria-label={recipe.title}><span className="recipe-tag">{recipe.cuisine} · {recipe.category}</span></div><div className="recipe-hero-copy"><div className="eyebrow muted">MADE FOR YOUR TABLE</div><h1>{recipe.title}</h1><p>{recipe.description}</p><div className="recipe-tags-line">{recipe.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="recipe-meta"><span><Clock3 size={15}/>{recipe.prepMinutes===undefined?'~':''}Prep {prep} min</span><span><Flame size={15}/>{recipe.cookMinutes===undefined?'~':''}Cook {cook} min</span><span><Clock3 size={15}/>Total {recipe.minutes} min</span><span><Users size={15}/>{servings} servings</span><span>{recipe.difficulty}</span></div><div className="recipe-actions"><button className="primary-button" onClick={onCook}><Play size={15} fill="currentColor"/> Start cooking</button><button className={`outline-button ${saved?'saved':''}`} onClick={onSave}><Bookmark size={15} fill={saved?'currentColor':'none'}/>{saved?'Saved':'Save'}</button><button className="action-button" onClick={()=>window.print()} aria-label="Print recipe"><Printer size={16}/></button><button className="action-button" onClick={()=>{void navigator.clipboard?.writeText(window.location.href)}} aria-label="Copy recipe link"><Share2 size={16}/></button></div></div></div>
    <div className="serving-adjust"><span><Users size={16}/><b>Adjust servings</b><small>Quantities update as you adjust.</small></span><div className="servings-control"><button aria-label="Decrease servings" onClick={()=>setServings(Math.max(1,servings-1))}><Minus size={13}/></button><b>{servings}</b><button aria-label="Increase servings" onClick={()=>setServings(Math.min(12,servings+1))}><Plus size={13}/></button></div></div>
    <div className="recipe-columns"><div className="recipe-summary-column"><div className="detail-card ingredients-detail"><div className="eyebrow muted">THE GOOD STUFF</div><h2>Ingredients</h2>{recipe.ingredients.map((ing,i)=>{const detail=recipe.ingredientDetails?.[i];const amount=detail?.quantity===null||detail?.quantity===undefined?'quantity not specified':`${Number((detail.quantity*servings/recipe.servings).toFixed(2))}${detail.unit?` ${detail.unit}`:''}`;return <div className="detail-ingredient" key={`${ing}-${i}`}><span>{ing}{detail?.have!==undefined&&<small className={`ingredient-status ${detail.have?'available':'needed'}`}>{detail.have?'In your kitchen':'Need to get'}</small>}{detail?.substitution&&<small className="ingredient-swap">Swap: {detail.substitution}</small>}</span><b>{amount}</b></div>})}{detailLoading&&<p className="enrich-status" role="status"><span className="spinner dark-spinner"/> Adding measured quantities and detailed cooking guidance…</p>}{detailError&&<p className="enrich-status" role="status">{detailError}</p>}<div className="nutrition-card"><div className="eyebrow muted">ESTIMATED NUTRITION PER SERVING</div>{nutrition?<><b className="calorie-count">Approx. {Math.round(nutrition.calories)} kcal <small>per serving</small></b><div className="macro-list">{[['Protein',nutrition.protein],['Carbohydrates',nutrition.carbohydrates],['Fat',nutrition.fat],...(nutrition.fiber===undefined?[]:[['Fiber',nutrition.fiber]]),...(nutrition.sugar===undefined?[]:[['Sugar',nutrition.sugar]])].map(([label,value])=><span key={String(label)}><b>{String(label)}</b><small>{Number(value).toFixed(0)} g</small></span>)}</div><small className="nutrition-disclaimer">Estimated from listed ingredient amounts using typical food-composition values. Actual nutrition varies.</small></>:<p className="nutrition-unavailable">Add measured quantities for all ingredients to see a useful nutrition estimate.</p>}</div><RecipeInfo recipe={recipe} servings={servings} fridgeIngredients={fridgeIngredients}/></div><section className="video-card" aria-labelledby="video-tutorial-heading"><div className="video-placeholder" aria-hidden="true"><span><Play size={20} fill="currentColor"/></span><small>WATCH & LEARN</small></div><div className="video-copy"><div className="eyebrow muted">WATCH & LEARN</div><h2 id="video-tutorial-heading">Video Tutorial</h2><p>Learn how to prepare {recipe.title} with a video tutorial.</p><a href={recipe.videoUrl||`https://www.youtube.com/results?search_query=${encodeURIComponent(`${recipe.title} ${recipe.cuisine} recipe cooking tutorial`)}`} target="_blank" rel="noopener noreferrer" className="primary-button">{recipe.videoUrl?'Watch Tutorial':'Find a Video'} <ExternalLink size={14}/></a></div></section></div>
      <div className="detail-card procedure-card"><div className="procedure-heading"><div><div className="eyebrow muted">PREPARATION</div><h2>Step-by-step cooking</h2><p>Clear instructions with measured ingredients, timing and useful cues.</p></div><button className="primary-button" onClick={onCook}><Play size={14}/> Cook mode</button></div><div className="recipe-detail-meta" aria-label="Recipe details"><span>{recipe.cuisine} cuisine</span><span>{recipe.mealType||recipe.category}</span><span>{recipe.difficulty}</span></div><div className="preparation-list">{preparationSteps.map((step,i)=><article key={`${i}-${step.title}`} className="preparation-step"><div className="preparation-step-label">STEP {i+1} OF {preparationSteps.length}</div><div className="preparation-step-heading"><span className="preparation-count" aria-label={`Step ${i+1} of ${preparationSteps.length}`}>{String(i+1).padStart(2,'0')}</span><h3>{step.title}</h3><span className="preparation-duration"><Clock3 size={13}/><span>{step.durationMinutes} min</span></span></div>{step.description.split(/\n{2,}/).map((paragraph,index)=><p key={`${i}-description-${index}`}>{paragraph}</p>)}{step.ingredients?.length>0&&<div className="preparation-ingredients"><b>Ingredients used</b><ul>{step.ingredients.map(name=>{const index=recipe.ingredientDetails?.findIndex(item=>item.name.toLowerCase()===name.toLowerCase())??-1;const item=index>=0?recipe.ingredientDetails?.[index]:undefined;const quantity=item&&item.quantity!==null&&item.quantity!==undefined?`${Number((item.quantity*servings/recipe.servings).toFixed(2))}${item.unit?` ${item.unit}`:''}`:'quantity not specified';return <li key={name}><span>{name}</span><span>{quantity}</span></li>})}</ul></div>}{step.tip&&<aside className="preparation-tip"><Sparkles size={14}/><b>Tip</b><span>{step.tip}</span></aside>}</article>)}</div><div className="visual-note"><Sparkles size={14}/> Cook Mode gives you one clear step at a time.</div></div></div>
    
  </section>;
}

function normalizedFoodName(value:string){return value.toLocaleLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim().replace(/ies$/,'y').replace(/s$/,'')}
function foodNamesMatch(left:string,right:string){const a=normalizedFoodName(left),b=normalizedFoodName(right);return !!a&&!!b&&(a===b||(a.length>=4&&b.includes(a))||(b.length>=4&&a.includes(b)))}
function detectedPotentialAllergens(ingredients:string[],declared:string[]=[]){
  const text=ingredients.join(' ').toLocaleLowerCase();
  const known:[string,RegExp][]=[['Dairy',/\b(milk|yogurt|yoghurt|cheese|paneer|butter|cream|ghee|whey)\b/i],['Wheat / gluten',/\b(wheat|barley|rye|bread|flour|semolina|pasta|lasagna|couscous|seitan)\b/i],['Egg',/\b(egg|eggs|mayonnaise)\b/i],['Peanuts',/\b(peanut|peanuts)\b/i],['Tree nuts',/\b(almond|cashew|walnut|pistachio|hazelnut|pecan)\b/i],['Soy',/\b(soy|soya|tofu|edamame)\b/i],['Fish',/\b(fish|salmon|tuna|cod|anchovy)\b/i],['Shellfish',/\b(shrimp|prawn|crab|lobster|shellfish)\b/i],['Sesame',/\b(sesame|tahini)\b/i]];
  const derived=known.filter(([,pattern])=>pattern.test(text)).map(([label])=>label);
  for(const label of declared){const knownLabel=known.find(([name])=>name.toLowerCase()===label.trim().toLowerCase());if(knownLabel&&knownLabel[1].test(text))derived.push(knownLabel[0])}
  return [...new Set(derived)];
}

function InfoCard({title,children,variant}:{title:string;children:React.ReactNode;variant?:'fridge'} ){return <section className={`${recipeInfoStyles.card} ${variant==='fridge'?recipeInfoStyles.fridgeCard:''}`}><h3>{title}</h3>{children}</section>}
function TimeAndServings({recipe,servings}:{recipe:Recipe;servings:number}){const prep=recipe.prepMinutes,cook=recipe.cookMinutes;return <InfoCard title="TIME & SERVINGS"><dl className={recipeInfoStyles.rows}><div><dt>Prep time</dt><dd>{prep===undefined?'Not listed':`${prep} min`}</dd></div><div><dt>Cook time</dt><dd>{cook===undefined?'Not listed':`${cook} min`}</dd></div><div><dt>Total time</dt><dd>{recipe.minutes?`${recipe.minutes} min`:'Not listed'}</dd></div><div><dt>Serves</dt><dd>{servings}</dd></div></dl></InfoCard>}
function DifficultyCard({difficulty}:{difficulty:Recipe['difficulty']}){const guidance=difficulty==='Easy'?'Straightforward steps and familiar techniques.':difficulty==='Medium'?'A few timing or preparation steps to manage.':'More involved preparation or cooking techniques.';return <InfoCard title="DIFFICULTY"><b className={recipeInfoStyles.difficulty}>{difficulty||'Not listed'}</b><p>{difficulty?guidance:'Difficulty has not been listed for this recipe.'}</p></InfoCard>}
function AllergenCard({allergens}:{allergens:string[]}){return <InfoCard title="POTENTIAL ALLERGENS"><p className={recipeInfoStyles.note}>Based on listed ingredients; always check product labels.</p>{allergens.length?<ul className={recipeInfoStyles.list}>{allergens.map(item=><li key={item}>{item}</li>)}</ul>:<p className={recipeInfoStyles.value}>No major allergens detected from the listed ingredients.</p>}</InfoCard>}
function ChefTips({tips}:{tips:string[]}){if(!tips.length)return null;return <InfoCard title="CHEF’S TIPS"><ul className={recipeInfoStyles.list}>{tips.map((tip,index)=><li key={`${index}-${tip}`}>{tip}</li>)}</ul></InfoCard>}
function FridgeMatch({recipe,fridgeIngredients}:{recipe:Recipe;fridgeIngredients:string[]}){
  const details=recipe.ingredientDetails||[];const hasExplicitAvailability=details.some(item=>typeof item.have==='boolean');
  if(fridgeIngredients.length===0&&!hasExplicitAvailability)return null;
  const ingredients=recipe.ingredients.map((name,index)=>({name,have:fridgeIngredients.some(item=>foodNamesMatch(item,name))||details[index]?.have===true}));
  if(!ingredients.length)return null;
  const available=ingredients.filter(item=>item.have).length;const percent=Math.round(available/ingredients.length*100);
  return <InfoCard title="WHAT YOU ALREADY HAVE" variant="fridge"><p className={recipeInfoStyles.note}>YOUR FRIDGE MATCH</p><ul className={recipeInfoStyles.matchList}>{ingredients.map(item=><li key={item.name} className={item.have?recipeInfoStyles.inFridge:recipeInfoStyles.missing}><span aria-hidden="true">{item.have?'✓':'○'}</span><span>{item.name}</span><small>{item.have?'Have it':'Missing'}</small></li>)}</ul><div className={recipeInfoStyles.matchSummary}><b>You have {available} of {ingredients.length} ingredients</b><span>{percent}%</span></div><div className={recipeInfoStyles.progress} role="progressbar" aria-label="Recipe ingredient match" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><span style={{width:`${percent}%`}}/></div></InfoCard>
}
function EstimatedCost({cost,servings}:{cost:NonNullable<Recipe['estimatedCost']>;servings:number}){if(!Number.isFinite(cost.amount)||cost.amount<0||!Number.isFinite(cost.forServings)||cost.forServings<1||!Number.isFinite(servings)||servings<1)return null;const total=cost.amount*servings/cost.forServings;const format=(value:number)=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency:/^[A-Z]{3}$/.test(cost.currency)?cost.currency:'INR',maximumFractionDigits:0}).format(value)}catch{return `${Math.round(value)} ${cost.currency||''}`.trim()}};return <InfoCard title="ESTIMATED COST"><div className={recipeInfoStyles.costGrid}><div><small>Total estimated cost</small><b>{format(total)}</b></div><div><small>Cost per serving</small><b>{format(total/servings)}</b></div></div><p className={recipeInfoStyles.note}>Estimate based on the recipe’s supplied price data.</p></InfoCard>}
function ServingSuggestions({items}:{items:string[]}){if(!items.length)return null;return <InfoCard title="SERVING SUGGESTIONS"><ul className={`${recipeInfoStyles.list} ${recipeInfoStyles.chips}`}>{items.map(item=><li key={item}>{item}</li>)}</ul></InfoCard>}
function Substitutions({items}:{items:{ingredient:string;substitute:string}[]}){if(!items.length)return null;return <InfoCard title="EASY SUBSTITUTIONS"><dl className={recipeInfoStyles.substitutions}>{items.map(item=><div key={`${item.ingredient}-${item.substitute}`}><dt>{item.ingredient}</dt><dd><ArrowRight size={13} aria-hidden="true"/>{item.substitute}</dd></div>)}</dl></InfoCard>}
function RecipeInfo({recipe,servings,fridgeIngredients}:{recipe:Recipe;servings:number;fridgeIngredients:string[]}){
  const potentialAllergens=detectedPotentialAllergens(recipe.ingredients,Array.isArray(recipe.allergens)?recipe.allergens.filter((item):item is string=>typeof item==='string'):[]);
  const listedSubstitutions=Array.isArray(recipe.substitutions)?recipe.substitutions.filter(item=>item&&typeof item.ingredient==='string'&&typeof item.substitute==='string'):[];
  const ingredientSubstitutions=(recipe.ingredientDetails||[]).filter(item=>typeof item.substitution==='string'&&item.substitution.trim()).map(item=>({ingredient:item.name,substitute:item.substitution!}));
  const substitutions=[...listedSubstitutions,...ingredientSubstitutions].filter((item,index,list)=>list.findIndex(other=>foodNamesMatch(other.ingredient,item.ingredient)&&foodNamesMatch(other.substitute,item.substitute))===index);
  const tips=Array.isArray(recipe.tips)?recipe.tips.filter((tip):tip is string=>typeof tip==='string'&&!!tip.trim()):[];
  const servingSuggestions=Array.isArray(recipe.servingSuggestions)?recipe.servingSuggestions.filter((item):item is string=>typeof item==='string'&&!!item.trim()):[];
  const hasCost=!!recipe.estimatedCost;
  return <div className={recipeInfoStyles.section} aria-label="More recipe information"><div className={recipeInfoStyles.grid}><TimeAndServings recipe={recipe} servings={servings}/><DifficultyCard difficulty={recipe.difficulty}/><AllergenCard allergens={potentialAllergens}/><ChefTips tips={tips}/></div><FridgeMatch recipe={recipe} fridgeIngredients={fridgeIngredients}/>{hasCost&&<EstimatedCost cost={recipe.estimatedCost!} servings={servings}/>}<ServingSuggestions items={servingSuggestions}/><Substitutions items={substitutions}/></div>;
}

function CookMode({recipe,servings,step,setStep,seconds,setSeconds,running,setRunning,onFinish,onExit}:{recipe:Recipe;servings:number;step:number;setStep:(n:number)=>void;seconds:number;setSeconds:(n:number)=>void;running:boolean;setRunning:(n:boolean)=>void;onFinish:()=>void;onExit:()=>void}){
  const steps=getPreparationSteps(recipe);const current=steps[step]||steps[0];const mins=Math.floor(seconds/60),secs=seconds%60;
  return <div className="cook-mode"><header className="cook-header"><button className="action-button" onClick={onExit} aria-label="Exit Cook Mode"><X size={18}/></button><div><b>{recipe.title}</b><small>Cook Mode · {step+1} of {steps.length}</small></div><button className="action-button" onClick={()=>document.documentElement.requestFullscreen?.()} aria-label="Full screen"><MoreHorizontal size={18}/></button></header><div className="cook-progress" role="progressbar" aria-label={`Cooking progress: step ${step+1} of ${steps.length}`} aria-valuemin={1} aria-valuemax={steps.length} aria-valuenow={step+1}><span style={{width:`${((step+1)/steps.length)*100}%`}}/></div><div className="cook-content"><div className="cook-illustration" style={recipeImage(recipe,900)}><span>{step===0?'🥕':step===1?'🔥':step===2?'🍲':'🌿'}</span></div><div className="cook-step-label">STEP {String(step+1).padStart(2,'0')} OF {steps.length}</div><h1>{current?.title}</h1>{(current?.description||'').split(/\n{2,}/).map((paragraph,index)=><p key={`cook-description-${index}`}>{paragraph}</p>)}{current&&current.ingredients.length>0&&<div className="cook-step-ingredients"><b>Ingredients used</b><ul>{current.ingredients.map(name=>{const item=recipe.ingredientDetails?.find(entry=>entry.name.toLowerCase()===name.toLowerCase());const qty=item&&item.quantity!==null&&item.quantity!==undefined?`${Number((item.quantity*servings/recipe.servings).toFixed(2))} ${item.unit}`:'quantity not specified';return <li key={name}>{name} — {qty}</li>})}</ul></div>}{current?.tip&&<aside className="cook-step-tip"><Sparkles size={15}/><div><b>Tip</b><p>{current.tip}</p></div></aside>}<div className="cook-step-duration"><Clock3 size={14}/>{current?.durationMinutes} min for this step</div><div className="cook-timer"><Timer size={19}/><b>{String(mins).padStart(2,'0')}:{String(secs).padStart(2,'0')}</b><button onClick={()=>{if(seconds===0)setSeconds((current?.durationMinutes||1)*60);setRunning(!running)}}>{running?<Pause size={15}/>:<Play size={15}/>} {running?'Pause':seconds?'Resume':'Start timer'}</button><button aria-label="Reset timer" onClick={()=>{setRunning(false);setSeconds(0)}}><RotateCcw size={15}/></button></div><div className="cook-controls"><button className="outline-button" disabled={step===0} onClick={()=>{setRunning(false);setSeconds(0);setStep(step-1)}}><ArrowLeft size={15}/> Previous</button>{step===steps.length-1?<button className="primary-button" onClick={onFinish}><Check size={16}/> Finish recipe</button>:<button className="primary-button" onClick={()=>{setRunning(false);setSeconds(0);setStep(step+1)}}>Next step <ArrowRight size={16}/></button>}</div></div><footer className="cook-footer"><button onClick={()=>{setRunning(false);setSeconds(0);setStep(0)}}>Start over</button><span>Keep your screen awake where supported</span></footer></div>;
}

function SearchPage({onOpen}:{onOpen:(r:Recipe)=>void}){
  const [query,setQuery]=useState(''),[results,setResults]=useState<SearchRecipe[]>([]),[provider,setProvider]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false),[recent,setRecent]=useState<string[]>([]);
  useEffect(()=>{try{setRecent(JSON.parse(localStorage.getItem('fridgechef:recent-searches')||'[]'))}catch{/* Ignore unavailable storage. */}},[]);
  async function submit(event?:React.FormEvent,term=query){event?.preventDefault();const clean=term.trim();if(!clean||loading)return;setQuery(clean);setLoading(true);setError('');setResults([]);setSearched(true);try{const response=await fetch(`/api/recipes/search?q=${encodeURIComponent(clean)}`);const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'Recipe search is temporarily unavailable. Please try again.');setResults(data.results||[]);setProvider(data.attribution||'');const next=[clean,...recent.filter(x=>x.toLowerCase()!==clean.toLowerCase())].slice(0,5);setRecent(next);localStorage.setItem('fridgechef:recent-searches',JSON.stringify(next))}catch(error){setError(error instanceof Error?error.message:'Check your internet connection and try again.')}finally{setLoading(false)}}
  return <section className="search-page"><div className="search-hero"><div className="search-copy"><div className="eyebrow muted"><Search size={13}/> RECIPE SEARCH</div><h1>Find the recipe.<br/><em>Let’s make it cookable.</em></h1><p>Enter a recipe name and we’ll find recipes from trusted cooking websites.</p><form onSubmit={e=>submit(e)} className="web-search-form"><Search size={18}/><label className="sr-only" htmlFor="web-search">Recipe name</label><input id="web-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. Chicken Biryani, Pasta Alfredo, Chocolate Cake"/><button className="primary-button" disabled={!query.trim()||loading}>{loading?<><span className="spinner"/> Searching…</>:<>Search Recipes <ArrowRight size={15}/></>}</button></form><small className="search-footnote"><Sparkles size={13}/> Links open at their original recipe publishers.</small></div><div className="search-art"><div className="search-art-photo"/><div className="search-art-card"><span>📖</span><b>Good things to cook</b><small>From trusted kitchens</small></div><span className="art-star">✳</span></div></div>
    {recent.length>0&&<div className="recent-searches"><b>RECENT SEARCHES</b>{recent.map(x=><button key={x} onClick={()=>submit(undefined,x)}>{x}</button>)}</div>}
    {loading&&<div className="search-result-area" aria-live="polite"><h2>Finding delicious recipes…</h2><div className="search-result-grid">{[1,2,3].map(i=><div className="search-skeleton" key={i}/>)}</div></div>}
    {!loading&&error&&<div className="search-status error-status" role="alert"><p>{error}</p><button className="outline-button" onClick={()=>submit(undefined,query)}>Try again <RotateCcw size={14}/></button></div>}
    {!loading&&searched&&!error&&results.length===0&&<EmptyState title="No recipes found." sub="Try another recipe name, such as Chicken Biryani or Chocolate Cake."/>}
    {!loading&&results.length>0&&<div className="search-result-area"><div className="section-heading"><div><div className="eyebrow muted">FRESH FROM THE WEB</div><h2>Recipes we found</h2><p>Results for “{query}”</p></div><span className="result-count">{results.length} recipes</span></div><div className="search-result-grid">{results.map(item=><article className="search-result-card" key={item.id}><div className="search-result-image" style={{backgroundImage:`url("${item.image||'/food-placeholder.svg'}"),url("/food-placeholder.svg")`}} role="img" aria-label={`${item.title} recipe image`}/><div className="search-result-body"><small>{item.source}{item.cuisine&&` · ${item.cuisine}`}</small><h3>{item.title}</h3>{item.snippet&&<p>{item.snippet}</p>}<a href={item.url} target="_blank" rel="noopener noreferrer">View Recipe <ExternalLink size={14}/></a></div></article>)}</div><p className="attribution">Search results provided by {provider||'the recipe search service'}. Recipe pages belong to their original publishers.</p></div>}
  </section>;
}

function LibraryPage({recipes,onOpen,onDelete,onGenerate,title='Your recipe box.',subtitle='Recipes you’ve saved for another lovely meal.'}:{recipes:Recipe[];onOpen:(r:Recipe)=>void;onDelete:(id:string)=>void;onGenerate:()=>void;title?:string;subtitle?:string}){const [query,setQuery]=useState('');const matches=recipes.filter(r=>`${r.title} ${r.cuisine} ${r.category} ${r.description} ${r.ingredients.join(' ')} ${r.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));return <section><div className="page-intro"><div><div className="eyebrow muted">A LITTLE COLLECTION OF GOOD IDEAS</div><h1>{title}</h1><p>{subtitle}</p></div><button className="primary-button" onClick={onGenerate}><Plus size={15}/> Make something new</button></div>{recipes.length>0&&<div className="discover-search"><Search size={17}/><input aria-label="Search saved recipes" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your collection…"/></div>}{matches.length?<div className="recipe-grid library-grid">{matches.map((r,i)=><div className="library-card-wrap" key={r.id}><RecipeCard recipe={r} index={i} onOpen={()=>onOpen(r)} saved onSave={()=>onDelete(r.id)}/><button className="library-delete" onClick={()=>onDelete(r.id)} aria-label={`Remove ${r.title}`}><X size={14}/></button></div>)}</div>:<EmptyState title={recipes.length?'No recipes match that search':'Your recipe collection is empty—let’s cook something!'} sub={recipes.length?'Try a different recipe name, cuisine, ingredient or tag.':'Save a recipe you love and it’ll be waiting here.'} action="Create a recipe" onClick={onGenerate}/>}</section>}

const pantryCategories=['Vegetables','Fruits','Grains','Dairy','Meat','Spices','Sauces','Pantry'];
function expiryDays(date:string|null){if(!date)return null;const today=new Date();const start=Date.UTC(today.getFullYear(),today.getMonth(),today.getDate());return Math.floor((Date.parse(`${date}T00:00:00Z`)-start)/86400000)}
function expiryState(date:string|null){const days=expiryDays(date);if(days===null)return{label:'No expiry date',kind:'unknown',detail:'Expiry not set'};if(days<0)return{label:'Expired',kind:'expired',detail:`Expired ${Math.abs(days)} day${Math.abs(days)===1?'':'s'} ago`};if(days<=2)return{label:'High risk',kind:'high',detail:days===0?'Expires today':`Expires in ${days} day${days===1?'':'s'}`};if(days<=5)return{label:'Medium risk',kind:'medium',detail:`Expires in ${days} days`};return{label:'Low risk',kind:'low',detail:`Expires in ${days} days`}}
function KitchenPage({items,suggestions,onSave,onDelete,onGenerate,onOpen,onFavorite}:{items:PantryItem[];suggestions:Recipe[];onSave:(item:Omit<PantryItem,'id'>&{id?:string})=>Promise<boolean>;onDelete:(id:string)=>void;onGenerate:()=>void;onOpen:(r:Recipe)=>void;onFavorite:(r:Recipe)=>void}){
  const [editing,setEditing]=useState<PantryItem|null>(null),[name,setName]=useState(''),[quantity,setQuantity]=useState('1'),[unit,setUnit]=useState('pieces'),[purchaseDate,setPurchaseDate]=useState(''),[expiryDate,setExpiryDate]=useState(''),[category,setCategory]=useState('Pantry'),[storage,setStorage]=useState(''),[formError,setFormError]=useState(''),[saving,setSaving]=useState(false);
  const unexpired=items.filter(item=>!item.expiry_date||(expiryDays(item.expiry_date)??-1)>=0);const soon=unexpired.filter(item=>{const days=expiryDays(item.expiry_date);return days!==null&&days>=0&&days<=5}).sort((a,b)=>(expiryDays(a.expiry_date)??999)-(expiryDays(b.expiry_date)??999));
  const suggested=soon.length?suggestions:[];
  function resetForm(){setEditing(null);setName('');setQuantity('1');setUnit('pieces');setPurchaseDate('');setExpiryDate('');setCategory('Pantry');setStorage('');setFormError('')}
  function edit(item:PantryItem){setEditing(item);setName(item.name);setQuantity(String(item.quantity));setUnit(item.unit);setPurchaseDate(item.purchase_date||'');setExpiryDate(item.expiry_date||'');setCategory(item.category);setStorage(item.storage_type||'');setFormError('')}
  async function submit(event:React.FormEvent){event.preventDefault();if(saving)return;if(!name.trim()){setFormError('Enter a food name.');return}const amount=Number(quantity);if(!Number.isFinite(amount)||amount<=0){setFormError('Enter a quantity greater than zero.');return}if(expiryDate&&purchaseDate&&expiryDate<purchaseDate){setFormError('Expiry date must be on or after purchase date.');return}setSaving(true);try{const ok=await onSave({...(editing?{id:editing.id}:{}),name:name.trim(),quantity:amount,unit,purchase_date:purchaseDate||null,expiry_date:expiryDate||null,category,storage_type:storage||null});if(ok)resetForm()}finally{setSaving(false)}}
  return <section><PageIntro eyebrow="YOUR PANTRY, AT A GLANCE" title={<>My <em>kitchen.</em></>} sub="Track what you have, when it expires, and what to cook next."/><div className="pantry-use-first"><div className="pantry-section-head"><div><div className="eyebrow muted">MAKE THE MOST OF WHAT YOU HAVE</div><h2>Use these first</h2><p>Fresh ingredients that are getting close to their best-by date.</p></div><button className="outline-button" onClick={onGenerate}><Sparkles size={14}/> Cook with these</button></div>{soon.length?<><div className="use-first-items">{soon.map(item=>{const state=expiryState(item.expiry_date);return <div key={item.id} className={`use-first-item risk-${state.kind}`}><span className="risk-dot"/><b>{item.name}</b><small>{state.detail}</small></div>})}</div>{suggested.length>0&&<><h3>Recipes that use these ingredients</h3><div className="recipe-grid kitchen-suggestions">{suggested.map((recipe,i)=><RecipeCard key={recipe.id} recipe={recipe} index={i} onOpen={()=>onOpen(recipe)} saved={false} onSave={()=>onFavorite(recipe)}/>)}</div></>}</>:<div className="pantry-good"><Check size={16}/> Nothing is close to expiry. Your ingredients are in good shape.</div>}</div>
    <div className="kitchen-panel pantry-panel"><div className="kitchen-top"><div><h2>Kitchen inventory</h2><p>Items are private to your signed-in account.</p></div><span className="inventory-count">{items.length} items</span></div>
    <form className="pantry-form" onSubmit={submit}><div className="pantry-form-grid"><label>Food or product<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Whole milk" required/></label><label>Quantity<input type="number" min="0.01" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value)}>{['pieces','g','kg','ml','L','cups','bottles','packs','cans','tbsp','tsp'].map(v=><option key={v}>{v}</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{pantryCategories.map(v=><option key={v}>{v}</option>)}</select></label><label>Purchase date <span className="optional-label">optional</span><input type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)}/></label><label>Expiry date <span className="optional-label">optional</span><input type="date" value={expiryDate} onChange={e=>setExpiryDate(e.target.value)}/></label><label>Storage <span className="optional-label">optional</span><select value={storage} onChange={e=>setStorage(e.target.value)}><option value="">Choose storage</option>{['Fridge','Freezer','Cupboard','Counter'].map(v=><option key={v}>{v}</option>)}</select></label></div>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="pantry-form-actions"><button className="primary-button" disabled={saving}>{saving?<><span className="spinner"/> Saving…</>:<><Plus size={15}/>{editing?'Update item':'Add to pantry'}</>}</button>{editing&&<button type="button" className="outline-button" onClick={resetForm}>Cancel</button>}</div></form>
    {items.length?<div className="pantry-table">{items.map(item=>{const state=expiryState(item.expiry_date);return <article className={`pantry-row risk-${state.kind}`} key={item.id}><span className="risk-dot"/><div className="pantry-item-copy"><b>{item.name}</b><small>{item.quantity} {item.unit} · {item.category}{item.storage_type?` · ${item.storage_type}`:''}</small></div><span className={`expiry-badge risk-${state.kind}`} aria-label={`${state.label}: ${state.detail}`}>{state.kind==='expired'?'⚠ ':''}{state.label}<small>{state.detail}</small></span><div className="pantry-row-actions"><button aria-label={`Edit ${item.name}`} onClick={()=>edit(item)}><Pencil size={14}/></button><button aria-label={`Delete ${item.name}`} onClick={()=>onDelete(item.id)}><X size={15}/></button></div></article>})}</div>:<EmptyState title="Your pantry is empty" sub="Add a few ingredients and FridgeChef will help you use them in time."/>}</div></section>
}

function SettingsPage({servings,setServings,cuisine,setCuisine,preferences,togglePreference,onSave,user}:{servings:number;setServings:(n:number)=>void;cuisine:string;setCuisine:(s:string)=>void;preferences:string[];togglePreference:(s:string)=>void;onSave:(value:{default_servings:number;favorite_cuisine:string;dietary_preferences:string[]})=>void;user:User|null}){return <section><PageIntro eyebrow="MAKE IT FEEL LIKE YOUR KITCHEN" title={<>Your cooking <em>preferences.</em></>} sub={user?`Signed in as ${user.email}. Set your defaults and keep them with your account.`:'Set a few defaults. Sign in to sync them with your account.'}/><div className="settings-card"><label>Default servings<div className="servings-control"><button onClick={()=>setServings(Math.max(1,servings-1))} aria-label="Decrease default servings"><Minus size={13}/></button><b>{servings}</b><button onClick={()=>setServings(Math.min(12,servings+1))} aria-label="Increase default servings"><Plus size={13}/></button></div></label><label>Favorite cuisine<select value={cuisine} onChange={e=>setCuisine(e.target.value)}>{cuisines.map(c=><option key={c}>{c}</option>)}</select></label><div><b>Dietary preferences</b><div className="diet-chips">{diets.map(d=><button key={d} className={preferences.includes(d)?'chosen':''} onClick={()=>togglePreference(d)}>{preferences.includes(d)&&<Check size={12}/>} {d}</button>)}</div></div><button className="primary-button" onClick={()=>onSave({default_servings:servings,favorite_cuisine:cuisine,dietary_preferences:preferences})}><Check size={15}/> Save preferences</button></div></section>}

function EmptyState({title,sub,action,onClick}:{title:string;sub:string;action?:string;onClick?:()=>void}){return <div className="empty-state"><span><ChefHat size={23}/></span><h2>{title}</h2><p>{sub}</p>{action&&onClick&&<button className="outline-button" onClick={onClick}>{action} <ArrowRight size={14}/></button>}</div>}
