import type { Recipe, PreparationStep } from './recipe-data';

type StepSeed = [string, string, number, string[], string?];
const preparations: Record<string, StepSeed[]> = {
  'Hyderabadi Chicken Biryani': [['Marinate the chicken','Coat chicken with yogurt, ginger, garlic and biryani spices. Rest while you prepare the rice.',15,['Chicken','Yogurt','Garam masala']],['Par-cook the rice','Rinse basmati rice until the water runs clear. Boil with whole spices until the grains are about three-quarters cooked, then drain.',12,['Basmati rice']],['Layer the biryani','Brown sliced onion in a heavy pot. Add the marinated chicken, then layer over the drained rice and fried onion.',10,['Onion','Chicken','Basmati rice']],['Steam and serve','Cover tightly and cook over low heat until the chicken is cooked through and the rice is tender. Rest briefly, then fluff gently.',33,['Chicken','Basmati rice']]],
  'Butter Chicken': [['Season the chicken','Cut chicken into even pieces and coat with yogurt, garam masala and a pinch of salt. Let it stand while the sauce starts.',10,['Chicken','Yogurt','Garam masala']],['Sear until golden','Heat a little oil in a wide pan over medium-high heat. Sear chicken in batches until browned outside; transfer to a plate.',10,['Chicken']],['Build the tomato sauce','Cook tomato with butter and garam masala until softened and fragrant. Blend until smooth if desired, then stir in cream.',15,['Tomato','Butter','Garam masala','Cream']],['Simmer and finish','Return chicken and its juices to the pan. Simmer gently until cooked through and the sauce coats a spoon.',10,['Chicken','Cream']]],
  'Paneer Tikka': [['Make the marinade','Stir yogurt, tikka masala and lemon juice together. Cut paneer and bell pepper into similarly sized pieces.',8,['Yogurt','Tikka masala','Lemon','Paneer','Bell pepper']],['Coat and rest','Fold paneer and pepper through the marinade until coated on all sides. Rest for at least 10 minutes.',10,['Paneer','Bell pepper','Yogurt']],['Char the paneer','Thread onto skewers or spread in a hot pan. Cook, turning carefully, until the edges are golden and lightly charred.',12,['Paneer','Bell pepper']],['Serve warm','Finish with a squeeze of lemon and serve while the paneer is hot and tender.',5,['Lemon']]],
  'Masala Dosa': [['Soak and ferment the batter','Soak rice and urad dal separately until softened. Drain, blend with a little water to a smooth, pourable batter, cover and ferment until airy and lightly bubbly.',15,['Rice','Urad dal']],['Cook the potato filling','Boil potatoes until fork-tender and break into chunks. Heat oil, crackle mustard seeds, add curry leaves and fold in potato; season and keep warm.',12,['Potato','Mustard seeds','Curry leaves']],['Spread the dosa','Heat a lightly oiled skillet over medium heat. Pour in a ladle of batter and spread outward in a thin, even circle.',3,['Rice','Urad dal']],['Crisp, fill and fold','Cook until the underside is golden and crisp. Spoon potato filling across the center, fold over and serve hot.',5,['Potato']]],
  'Chole': [['Prepare the chickpeas','Drain soaked chickpeas. If using dried chickpeas, pressure-cook or simmer until tender; reserve a little cooking liquid.',10,['Chickpeas']],['Cook the masala','Sauté chopped onion until soft and golden. Add ginger, tomato and chole masala; cook until the tomato breaks down and the mixture smells fragrant.',12,['Onion','Ginger','Tomato','Chole masala']],['Simmer together','Stir in chickpeas and enough cooking liquid to make a thick curry. Simmer until the flavors come together, lightly mashing a few chickpeas to thicken.',15,['Chickpeas']],['Season and serve','Taste for salt and spice, then serve the hot chole with rice or flatbread.',3,['Chickpeas']]],
  'Rajma Chawal': [['Cook the kidney beans','Drain soaked kidney beans and simmer in fresh water until completely tender. Keep some cooking liquid for the curry.',10,['Kidney beans']],['Make the onion-tomato base','Sauté onion until golden. Add cumin and tomato; cook until soft and the oil begins to show at the edges.',12,['Onion','Cumin','Tomato']],['Simmer the rajma','Add kidney beans and a cup of their cooking liquid. Cover and simmer gently until the gravy is creamy; mash a few beans to thicken.',25,['Kidney beans']],['Cook and serve the rice','Cook rice until fluffy. Taste the rajma for seasoning and ladle it over warm rice.',8,['Rice']]],
  'Palak Paneer': [['Blanch the spinach','Wash spinach well and blanch briefly in boiling water. Cool, drain and blend to a smooth puree.',8,['Spinach']],['Prepare the paneer','Cut paneer into bite-sized cubes. Sear lightly in a little oil if you prefer a golden outside, then set aside.',5,['Paneer']],['Cook the spinach gravy','Sauté garlic and cumin until fragrant. Add spinach puree and simmer gently; stir in a little cream if desired.',10,['Garlic','Cumin','Spinach','Cream']],['Finish the curry','Fold paneer into the gravy and warm through without boiling hard. Taste, season and serve.',7,['Paneer']]],
  'Aloo Paratha': [['Make the dough and filling','Knead whole wheat flour with water into a soft dough. Mash cooked potato with coriander and green chili until evenly seasoned.',15,['Whole wheat flour','Potato','Coriander','Green chili']],['Fill and seal','Roll a dough portion into a small round, add potato filling in the center, gather the edges and pinch closed.',8,['Whole wheat flour','Potato']],['Roll gently','Dust lightly with flour and roll the stuffed dough into an even round, taking care not to let the filling break through.',5,['Whole wheat flour']],['Griddle until golden','Cook on a hot skillet, turning once bubbles appear. Brush with butter and cook both sides until golden spots form.',12,['Butter']]],
  'Poha': [['Rinse the poha','Place poha in a sieve and rinse briefly until just softened. Drain well so the flakes stay separate.',4,['Poha']],['Make the tempering','Heat oil, crackle mustard seeds and add curry leaves and chopped onion. Cook until the onion is soft and translucent.',6,['Onion','Curry leaves']],['Toss and warm','Add peanuts and turmeric, then fold in drained poha gently. Cover briefly on low heat until hot throughout.',7,['Peanuts','Poha']],['Finish with lemon','Season to taste, fluff gently and finish with lemon juice before serving.',3,['Lemon']]],
  'Vegetable Pulao': [['Rinse the rice','Rinse basmati rice until the water is mostly clear, then soak briefly and drain. Cut vegetables into small even pieces.',8,['Basmati rice','Carrot','Peas','Green beans']],['Bloom the spices','Warm oil in a pot. Add whole spices or garam masala and stir briefly until aromatic, taking care not to scorch them.',3,['Garam masala']],['Toast vegetables and rice','Add vegetables and drained rice. Stir gently so the grains are coated with the spices.',5,['Carrot','Peas','Green beans','Basmati rice']],['Simmer until fluffy','Add measured water and salt, cover and cook over low heat until rice is tender and liquid is absorbed. Rest, then fluff.',19,['Basmati rice']]],
  'Dal Tadka': [['Rinse and cook the lentils','Rinse lentils until the water runs clearer. Simmer with turmeric and water until soft enough to mash easily.',20,['Lentils','Turmeric']],['Prepare the garlic tadka','Heat ghee or oil in a small pan. Add cumin and sliced garlic; stir until the garlic is golden, not dark.',4,['Cumin','Garlic']],['Season the dal','Add chopped tomato to the tadka and cook until soft. Pour the sizzling mixture into the cooked lentils and stir.',7,['Tomato','Garlic','Cumin','Lentils']],['Adjust and serve','Add hot water to reach your preferred consistency. Simmer a few minutes, taste for salt and serve warm.',4,['Lentils']]],
  'Chicken Curry': [['Season the chicken','Cut chicken into even pieces and season lightly. Chop onion and tomato so they are ready before the pan heats.',8,['Chicken','Onion','Tomato']],['Brown the aromatics','Heat oil over medium heat. Cook onion until golden, then add ginger and coriander; stir until fragrant.',8,['Onion','Ginger','Coriander']],['Cook the curry base','Add tomato and cook until pulpy. Stir in chicken and turn the pieces to coat them in the masala.',8,['Tomato','Chicken']],['Simmer until cooked through','Cover and cook gently, stirring occasionally, until chicken reaches 74°C/165°F and the gravy thickens.',20,['Chicken']]],
  'Goan Fish Curry': [['Prepare the curry base','Blend coconut milk with tamarind, chili and turmeric until evenly combined. Cut fish into large pieces and pat dry.',8,['Coconut milk','Tamarind','Chili','Turmeric','White fish']],['Simmer the sauce','Warm the curry base in a wide pan over medium-low heat. Stir gently and bring it to a quiet simmer.',8,['Coconut milk']],['Poach the fish','Nestle fish into the sauce in one layer. Simmer gently, turning once, until opaque and just flaking; avoid vigorous boiling.',10,['White fish']],['Balance and serve','Taste the sauce for tang and salt. Serve promptly with rice so the fish stays tender.',3,['White fish']]],
  'Egg Curry': [['Boil and prepare the eggs','Boil eggs until set, cool under water, peel and halve. Make a few shallow cuts in each white so the sauce can cling.',10,['Eggs']],['Cook the onion masala','Sauté chopped onion until golden. Add ginger and garam masala and stir briefly until fragrant.',8,['Onion','Ginger','Garam masala']],['Soften the tomato','Add tomato and cook until it breaks down into a thick sauce. Add a splash of water if the pan becomes dry.',8,['Tomato']],['Warm the eggs in the curry','Add a little water to loosen the gravy, then nestle in eggs and simmer gently for a few minutes. Season and serve.',4,['Eggs']]],
  'Mutton Rogan Josh': [['Brown the lamb','Pat lamb dry. Brown in batches in a heavy pot over medium-high heat so the pieces color instead of steaming.',15,['Lamb']],['Build the spiced base','Lower the heat. Stir yogurt in gradually with Kashmiri chili, fennel and ginger, keeping the mixture smooth.',10,['Yogurt','Kashmiri chili','Fennel','Ginger']],['Braise until tender','Return lamb and juices to the pot. Cover and cook gently, stirring occasionally, until fork-tender; add water if needed.',65,['Lamb']],['Rest and finish','Skim excess fat if desired. Rest briefly, taste for seasoning and serve hot.',5,['Lamb']]],
  'Chicken 65': [['Marinate the chicken','Cut chicken into bite-sized pieces. Coat with yogurt, chili and rice flour; rest briefly so the seasoning adheres.',12,['Chicken','Yogurt','Chili','Rice flour']],['Fry until crisp','Shallow-fry in batches in hot oil until crisp and the centers reach 74°C/165°F. Drain on a rack or paper.',18,['Chicken']],['Temper the curry leaves','In a clean pan, warm a little oil and briefly fry curry leaves and chili until fragrant.',3,['Curry leaves','Chili']],['Toss and serve','Add crisp chicken and toss quickly to coat. Serve straight away while the coating is crunchy.',2,['Chicken']]],
  'Pav Bhaji': [['Boil the vegetables','Cut potato and cauliflower into chunks. Simmer with peas until all are fork-tender, then drain lightly.',15,['Potato','Cauliflower','Peas']],['Cook the bhaji masala','Sauté tomato in butter until soft. Stir in pav bhaji masala and cook until fragrant.',8,['Tomato','Pav bhaji masala','Butter']],['Mash and simmer','Add boiled vegetables and mash into a chunky mixture. Simmer, stirring, until thick and well combined.',12,['Potato','Cauliflower','Peas']],['Toast the pav','Split rolls and toast cut sides in butter until golden. Serve alongside bhaji with lemon.',5,['Pav bhaji masala','Butter']]],
  'Idli Sambar': [['Prepare the sambar vegetables','Cut carrot and drumstick into even pieces. Rinse lentils and simmer separately until soft.',12,['Carrot','Drumstick','Lentils']],['Simmer the sambar','Cook vegetables with lentils, water and sambar spices until tender and the broth is flavorful.',20,['Lentils','Carrot','Drumstick']],['Steam the idlis','Pour fermented idli batter into greased molds and steam until a tester comes out clean.',12,['Rice','Urad dal']],['Serve together','Rest idlis briefly before unmolding. Ladle hot sambar alongside the soft steamed cakes.',3,['Rice','Lentils']]],
  'Lemon Rice': [['Prepare the rice','Cook rice until tender but separate, then spread it briefly to cool so the grains do not clump.',12,['Rice']],['Make the lemon tempering','Heat oil and crackle mustard seeds. Add peanuts, curry leaves and turmeric; stir until peanuts are toasted.',5,['Peanuts','Curry leaves','Turmeric']],['Combine gently','Turn off the heat. Add lemon juice and cooked rice, folding gently so the grains stay intact.',3,['Lemon','Rice']],['Taste and serve','Check salt and lemon balance, then serve warm or at room temperature.',2,['Lemon']]],
  'Paneer Butter Masala': [['Sear the paneer','Cut paneer into cubes and sear lightly in a warm pan until just golden. Remove before it dries out.',5,['Paneer']],['Cook the tomato-cashew base','Simmer tomato and cashews until soft. Blend smooth, taking care with hot liquid.',12,['Tomato','Cashews']],['Make the creamy gravy','Return puree to the pan with butter and spices. Simmer gently, then stir in cream.',10,['Butter','Cream']],['Finish with paneer','Fold paneer through the gravy and warm for a few minutes without boiling. Taste and serve.',5,['Paneer']]],
  'Margherita Pizza': [['Heat the oven','Heat oven as high as it safely goes, ideally 240°C/475°F or higher. Place a tray or stone inside to preheat.',10,['Pizza dough']],['Shape and top','Stretch dough into a thin round. Spread a light layer of tomato over it and add mozzarella, leaving a small border.',6,['Pizza dough','Tomato','Mozzarella']],['Bake until blistered','Transfer to the hot tray and bake until the crust puffs and browns and the cheese bubbles.',10,['Pizza dough','Mozzarella']],['Finish with basil','Scatter fresh basil and a little olive oil over the hot pizza. Rest briefly, slice and serve.',4,['Basil','Olive oil']]],
  'Pasta Alfredo': [['Boil the pasta','Cook pasta in well-salted boiling water until just al dente. Reserve a mug of pasta water before draining.',10,['Pasta']],['Warm the cream sauce','Melt butter over low heat. Add cream and warm gently; do not let it boil hard.',5,['Butter','Cream']],['Toss until glossy','Add drained pasta and parmesan, tossing over low heat. Loosen with reserved pasta water a splash at a time.',7,['Parmesan','Black pepper']],['Season and serve','Taste before adding salt, since parmesan is salty. Finish with black pepper and serve immediately.',3,['Black pepper']]],
  'Vegetable Lasagna': [['Prepare the vegetables','Cut zucchini and other vegetables evenly. Roast or sauté until softened and excess moisture has evaporated.',15,['Zucchini']],['Layer the lasagna','Spread tomato sauce in a baking dish. Add pasta sheets, vegetables and ricotta in even layers; repeat and finish with mozzarella.',15,['Lasagna sheets','Tomato','Ricotta','Mozzarella']],['Bake until tender','Cover and bake until pasta is tender, then uncover so the cheese turns golden and bubbling.',38,['Lasagna sheets','Mozzarella']],['Rest before slicing','Leave the lasagna to stand so the layers set. Cut into portions and serve warm.',7,['Mozzarella']]],
  'Chicken Tacos': [['Season the chicken','Pat chicken dry and coat evenly with paprika, salt and a little oil. Slice avocado and prepare lime.',8,['Chicken','Paprika','Avocado','Lime']],['Sear and rest','Cook chicken in a hot pan until browned and cooked through to 74°C/165°F. Rest briefly, then slice across the grain.',14,['Chicken']],['Warm the tortillas','Warm tortillas in a dry skillet until pliable and lightly toasted, stacking them under a clean towel.',3,['Tortillas']],['Assemble the tacos','Fill tortillas with sliced chicken and avocado. Add lime and any salsa or crunchy toppings, then serve.',5,['Tortillas','Avocado','Lime']]],
  'Black Bean Enchiladas': [['Prepare the filling','Drain black beans and mix with corn and a little cheese. Warm tomato sauce so it spreads easily.',8,['Black beans','Corn','Cheddar','Tomato sauce']],['Fill and roll','Spoon filling into tortillas, roll snugly and place seam-side down in a lightly sauced baking dish.',10,['Tortillas','Black beans','Tomato sauce']],['Cover and bake','Pour remaining sauce over the rolls and scatter cheddar on top. Bake until hot throughout and bubbling.',25,['Tomato sauce','Cheddar']],['Rest and serve','Rest for a few minutes so the rolls hold together, then serve warm.',5,['Black beans','Tortillas']]],
  'Veg Fried Rice': [['Prep everything first','Dice carrot and have peas, cooked cold rice, eggs and soy sauce ready beside the wok; high-heat cooking moves quickly.',8,['Carrot','Peas','Rice','Eggs','Soy sauce']],['Scramble the eggs','Heat a wok until hot, add a little oil and scramble eggs just until set. Remove to a plate.',3,['Eggs']],['Stir-fry the vegetables','Add a little more oil and stir-fry carrot and peas until crisp-tender. Add rice and break up clumps.',6,['Carrot','Peas','Rice']],['Season and toss','Return egg to the wok, add soy sauce and toss over high heat until the rice is hot. Taste before adding salt.',3,['Soy sauce']]],
  'Pad Thai': [['Soften the noodles','Soak rice noodles in warm water until pliable but still slightly firm. Drain well.',10,['Rice noodles']],['Mix the sauce and prepare tofu','Stir tamarind with the recipe’s sweet-salty seasonings. Pat tofu dry and cut into small pieces.',5,['Tamarind','Tofu']],['Cook the noodles','Sear tofu, add noodles and sauce, then toss quickly until noodles are tender and coated. Push aside and scramble egg.',12,['Tofu','Rice noodles','Eggs']],['Finish with peanuts','Fold everything together and serve with crushed peanuts. Taste and balance with more tamarind if needed.',4,['Peanuts','Tamarind']]],
  'Bibimbap': [['Prepare the rice and vegetables','Cook rice until fluffy. Slice carrot and prepare spinach; cook each vegetable separately until tender but still colorful.',15,['Rice','Spinach','Carrot']],['Season each topping','Season vegetables lightly and keep them in separate piles so the bowl stays colorful.',8,['Spinach','Carrot']],['Cook the egg','Fry eggs in a lightly oiled pan until whites are set and yolks remain as runny as preferred.',4,['Eggs']],['Assemble the bowls','Divide rice between bowls, arrange vegetables around the top and add gochujang and egg. Mix at the table.',5,['Rice','Gochujang','Eggs']]],
  'Greek Salad': [['Prepare the vegetables','Wash and dry cucumber and tomato. Cut into bite-sized pieces and slice olives if desired.',8,['Cucumber','Tomato','Olives']],['Mix the dressing','Whisk lemon with olive oil, salt and black pepper until lightly emulsified.',2,['Lemon']],['Toss gently','Combine cucumber, tomato and olives with dressing. Fold in feta near the end so it keeps its shape.',3,['Cucumber','Tomato','Olives','Lemon','Feta']],['Serve fresh','Taste and adjust lemon or seasoning. Serve right away while the vegetables are crisp.',2,['Cucumber','Tomato','Lemon']]],
  'Shakshuka': [['Soften the peppers','Heat oil in a covered skillet. Cook sliced onion and bell pepper over medium heat until soft and sweet.',8,['Onion','Bell pepper']],['Simmer the tomato sauce','Add tomato and paprika; simmer until thick enough to hold a spoon trail.',12,['Tomato','Paprika']],['Poach the eggs','Make small wells in the sauce and crack in eggs. Cover and cook gently until whites are set and yolks suit your preference.',10,['Eggs']],['Season and serve','Taste the sauce, season and bring the skillet to the table with bread for dipping.',5,['Eggs']]],
  'Falafel Bowl': [['Soak and season the chickpeas','Use soaked dried chickpeas for best texture; drain very well and pulse with parsley and cumin until coarse, not pasty.',10,['Chickpeas','Parsley','Cumin']],['Shape and crisp the falafel','Form small patties and pan-fry in a thin layer of oil, turning until browned and hot through.',18,['Chickpeas']],['Prepare the bowl','Slice cucumber and arrange it with greens or grains. Stir tahini with water and lemon until pourable.',8,['Cucumber','Tahini']],['Assemble and serve','Add warm falafel to each bowl and drizzle with tahini. Serve while crisp.',4,['Tahini','Cucumber']]],
  'Mac and Cheese': [['Boil the macaroni','Cook macaroni in salted boiling water until just tender. Drain, reserving a little cooking water.',10,['Macaroni']],['Make the cheese sauce','Melt butter over medium-low heat. Whisk in milk gradually until smooth and lightly thickened.',6,['Butter','Milk']],['Melt in the cheddar','Lower the heat and add cheddar and mustard, stirring until smooth. Avoid boiling so the sauce stays silky.',5,['Cheddar','Mustard']],['Combine and serve','Fold macaroni into the sauce. Loosen with a splash of pasta water if needed and serve hot.',4,['Macaroni']]],
  'Grilled Salmon': [['Season the salmon','Pat salmon dry and season with black pepper, lemon and a little olive oil. Preheat grill or grill pan.',5,['Salmon','Lemon','Olive oil','Black pepper']],['Grill the first side','Place salmon skin-side down if applicable. Cook without moving until the fish releases easily and the edges turn opaque.',6,['Salmon']],['Turn and finish','Turn carefully and cook until just opaque and flaky, or 63°C/145°F at the thickest point for food safety.',6,['Salmon']],['Rest and garnish','Rest briefly, add dill and another squeeze of lemon, then serve.',3,['Dill','Lemon']]],
  'Mushroom Risotto': [['Warm the stock','Warm stock in a saucepan and keep it at a gentle simmer. Slice mushrooms evenly.',5,['Stock','Mushrooms']],['Brown the mushrooms','Sauté mushrooms in butter until browned and their released liquid evaporates. Set some aside for topping.',8,['Mushrooms','Butter']],['Toast and slowly cook the rice','Toast arborio rice briefly, then add warm stock a ladle at a time, stirring and waiting for each addition to absorb.',27,['Arborio rice','Stock']],['Finish until creamy','Stir in mushrooms and parmesan when rice is tender with a slight bite. Rest a minute, then serve.',5,['Parmesan','Mushrooms']]],
  'Chicken Noodle Soup': [['Prepare the soup base','Cut carrot and celery into small even pieces. Bring stock to a gentle simmer in a large pot.',8,['Carrot','Celery','Stock']],['Cook the chicken','Add chicken and simmer gently until cooked through to 74°C/165°F. Lift out and shred once cool enough to handle.',20,['Chicken','Stock']],['Simmer the vegetables and noodles','Add carrot and celery until nearly tender, then add egg noodles and cook according to their package timing.',12,['Carrot','Celery','Egg noodles']],['Return chicken and season','Return shredded chicken to the broth. Taste for salt and pepper, warm through and serve.',5,['Chicken']]],
  'Mango Lassi': [['Prepare the mango','Peel and dice ripe mango, or measure thawed mango chunks. Chill ingredients for a cooler drink.',4,['Mango']],['Blend until smooth','Blend mango with yogurt, milk and a pinch of cardamom until creamy. Add honey only if the fruit needs sweetness.',3,['Mango','Yogurt','Milk','Cardamom','Honey']],['Adjust the texture','Add a little more milk for a thinner lassi or a few ice cubes for a colder drink, then blend briefly.',2,['Milk']],['Serve chilled','Pour into glasses and serve immediately; stir if it stands and separates.',1,['Mango']]],
};

// Complex recipes get extra, recipe-specific stages instead of splitting one
// generic instruction into artificial steps. Durations are active minutes and
// any long soak/ferment/rest is called out in the relevant tip.
const expandedPreparations: Record<string, StepSeed[]> = {
  'Hyderabadi Chicken Biryani': [
    ['Prepare the marinade','Cut the chicken into similar-sized pieces so they cook evenly. Stir yogurt, grated ginger, minced garlic and garam masala together in a bowl.',8,['Chicken','Yogurt','Garam masala','Ginger','Garlic'],'Wash your hands and the board after handling raw chicken.'],
    ['Marinate the chicken','Turn the chicken through the yogurt mixture until every piece is coated. Cover and chill while you prepare the rice; keep raw-chicken utensils separate.',10,['Chicken','Yogurt'],'A short rest seasons the surface; refrigerate if marinating longer than 30 minutes.'],
    ['Rinse and par-cook the rice','Rinse basmati rice several times until the water is mostly clear. Boil in plenty of salted water until the grains are tender at the edges but still firm in the center, then drain.',12,['Basmati rice'],'The rice will finish steaming in the pot, so drain it before it becomes fully soft.'],
    ['Soften and brown the onion','Slice the onion evenly. Warm oil in a heavy, lidded pot over medium heat and cook, stirring often, until soft with golden edges.',8,['Onion'],'Lower the heat if the onion darkens before it softens.'],
    ['Cook the marinated chicken','Add the chicken and marinade to the pot. Stir over medium heat until the outside loses its raw look and the sauce begins bubbling gently.',7,['Chicken','Yogurt'],'Scrape the bottom of the pot so the yogurt masala does not catch.'],
    ['Layer the rice and steam','Spread the drained rice over the chicken, cover tightly and cook on the lowest heat until the chicken reaches 74°C/165°F and the rice is tender.',20,['Basmati rice','Chicken'],'If the lid does not seal well, place a clean kitchen towel under it, keeping fabric away from the flame.'],
    ['Rest, fluff and serve','Turn off the heat and leave the pot covered for 5 minutes. Lift the rice gently with a fork or wide spoon, bringing some chicken up through the layers.',5,['Basmati rice','Chicken'],'Fluff gently rather than stirring hard so the rice grains stay intact.'],
  ],
  'Butter Chicken': [
    ['Cut and marinate the chicken','Cut chicken into even bite-sized pieces. Coat with yogurt and garam masala, then refrigerate while you prepare the sauce ingredients.',8,['Chicken','Yogurt','Garam masala'],'Even pieces finish cooking at roughly the same time.'],
    ['Sear the chicken in batches','Heat a wide pan over medium-high heat with a little oil. Brown the chicken in a single layer, turning once; move it to a clean plate before it is fully cooked.',8,['Chicken'],'Crowding traps steam; work in batches for browned edges.'],
    ['Soften the tomato base','Reduce heat to medium. Add tomato and cook, stirring, until it breaks down into a soft, thick base and no watery liquid pools around it.',8,['Tomato'],'If the base sticks, lower the heat and add a spoonful of water.'],
    ['Bloom the spices and butter','Stir garam masala and butter into the tomato base for about 30 seconds, until fragrant. Add a splash of water if the pan looks dry.',4,['Tomato','Garam masala','Butter'],'Spices should smell fragrant, not smoky or burnt.'],
    ['Simmer chicken in the sauce','Return chicken and any juices to the pan. Add cream, then simmer gently over medium-low heat, stirring occasionally, until chicken reaches 74°C/165°F.',13,['Chicken','Cream'],'Keep the sauce at a gentle bubble; a hard boil can split the cream.'],
    ['Taste and finish the curry','Turn off the heat, taste the sauce and adjust salt only if needed. Let it stand for 2 minutes, then serve with rice or flatbread.',4,['Cream'],'The sauce should coat a spoon; loosen with a little water if it becomes too thick.'],
  ],
  'Masala Dosa': [
    ['Soak the rice and urad dal','Rinse rice and urad dal separately, then cover each with fresh water and soak until softened. Drain before blending.',5,['Rice','Urad dal'],'Traditional batter needs several hours of soaking and an overnight ferment; that waiting time is not included in active cooking time.'],
    ['Blend and ferment the batter','Blend the drained rice and urad dal with only enough water to make a thick, pourable batter. Cover and ferment in a warm place until airy and lightly bubbly.',10,['Rice','Urad dal'],'If using ready-fermented batter, bring it close to room temperature and stir gently before cooking.'],
    ['Boil and break up the potatoes','Boil potatoes until a fork slides into the center easily. Drain, cool until safe to handle, peel if desired and break into bite-sized pieces.',12,['Potato'],'Do not mash completely; small pieces give the filling texture.'],
    ['Season the potato filling','Warm oil in a skillet over medium heat. Add mustard seeds; when they begin to pop, add curry leaves and potato, then stir gently until coated and hot.',8,['Potato','Mustard seeds','Curry leaves'],'Stand back slightly when adding curry leaves because damp leaves can splutter.'],
    ['Spread the batter on a hot skillet','Heat a flat skillet over medium heat and wipe with a thin film of oil. Pour on a ladle of batter and spread outward in a thin circle.',5,['Rice','Urad dal'],'If the batter tears or will not spread, let the skillet cool slightly before the next dosa.'],
    ['Crisp, fill and fold the dosa','Cook until the top looks dry and the underside is golden. Add potato filling down the center, fold the dosa over it and serve while crisp.',10,['Rice','Urad dal','Potato'],'Do not cover the dosa while it cooks; trapped steam softens the crisp base.'],
  ],
  'Rajma Chawal': [
    ['Rinse and soak the kidney beans','Pick through dried kidney beans, rinse, then soak in plenty of water until plump. Drain and discard the soaking water before cooking.',5,['Kidney beans'],'Allow at least 8 hours for soaking; use canned beans only if the recipe calls for them.'],
    ['Cook the beans until tender','Cover beans with fresh water and pressure-cook or simmer until completely soft. Test one: it should crush easily between your fingers; reserve some cooking liquid.',10,['Kidney beans'],'Never taste kidney beans that are still hard or undercooked.'],
    ['Rinse and start the rice','Rinse rice until the water is mostly clear. Add to a saucepan with the recipe-measured water and a pinch of salt.',5,['Rice'],'Rinsing removes loose starch and helps the cooked grains stay separate.'],
    ['Cook the onion-tomato masala','Heat oil in a heavy pan over medium heat. Cook chopped onion until golden, then add cumin and tomato; stir until the tomato is soft and thick.',12,['Onion','Cumin','Tomato'],'If the masala catches, reduce heat and add a small splash of water.'],
    ['Simmer the beans in the gravy','Add kidney beans and enough reserved liquid to make a loose curry. Cover partially and simmer gently, stirring now and then, until the gravy thickens.',18,['Kidney beans'],'Mash a few beans against the pan to thicken the sauce without adding extra ingredients.'],
    ['Rest the rice and serve','Cook rice until tender and the water is absorbed. Rest covered for 5 minutes, fluff with a fork, taste the rajma for salt and serve together.',5,['Rice','Kidney beans'],'Keep the rice covered while the curry finishes so it stays warm.'],
  ],
  'Palak Paneer': [
    ['Wash and wilt the spinach','Rinse spinach in several changes of water. Drop it into boiling water briefly until wilted, then transfer to cool water and drain well.',6,['Spinach'],'Cooling quickly helps the spinach keep a fresh green color.'],
    ['Blend the spinach smoothly','Blend the drained spinach into a smooth puree, adding only a small splash of water if the blades need help.',3,['Spinach'],'Avoid adding too much water; a thick puree makes a more flavorful gravy.'],
    ['Cut and lightly sear the paneer','Cut paneer into even cubes. Warm a little oil in a pan over medium heat and turn the cubes until lightly golden on two sides; remove to a plate.',6,['Paneer'],'Do not fry paneer for too long or it can become chewy.'],
    ['Cook the garlic and cumin','Lower the pan to medium-low and add garlic and cumin. Stir for 20–30 seconds until fragrant, keeping the garlic pale rather than brown.',3,['Garlic','Cumin'],'Burnt garlic can make the whole curry bitter.'],
    ['Simmer the spinach gravy','Add spinach puree and a small splash of water. Simmer gently, stirring often, until hot and slightly thickened; stir in cream if listed.',8,['Spinach','Cream'],'Use a gentle simmer rather than a rapid boil to preserve color and texture.'],
    ['Warm the paneer and finish','Fold paneer into the gravy and warm for 2–3 minutes. Taste, adjust seasoning and serve with rice or flatbread.',5,['Paneer'],'Add a spoonful of water if the gravy thickens too much while reheating.'],
  ],
  'Vegetable Pulao': [
    ['Rinse and soak the rice','Rinse basmati rice until the water is almost clear, then soak briefly and drain. Cut carrot, peas and green beans into small, even pieces.',7,['Basmati rice','Carrot','Peas','Green beans'],'Even vegetable pieces cook through alongside the rice.'],
    ['Warm the pot and bloom the spices','Heat oil in a lidded pot over medium heat. Add garam masala and stir for 20–30 seconds until aromatic.',3,['Garam masala'],'If the spice smell turns sharp or smoky, lower the heat immediately.'],
    ['Soften the vegetables','Add carrot, peas and green beans. Stir for 2–3 minutes so they are coated with the spiced oil and begin to soften.',4,['Carrot','Peas','Green beans'],'Keep stirring so spices do not settle and scorch on the pot base.'],
    ['Coat the rice grains','Add drained rice and fold gently through the vegetables for about a minute, taking care not to break the grains.',3,['Basmati rice'],'A gentle fold keeps the rice from turning mushy.'],
    ['Simmer the pulao covered','Add the recipe-measured water and salt. Bring to a boil, cover, then reduce to low heat until the water is absorbed and rice is tender.',15,['Basmati rice'],'Lift the lid only near the end; trapped steam cooks the top layer evenly.'],
    ['Rest and fluff the rice','Turn off the heat and rest covered for 5 minutes. Separate the grains gently with a fork, taste and serve.',5,['Basmati rice'],'If the rice is still firm, sprinkle on a little water and steam covered for a few more minutes.'],
  ],
  'Dal Tadka': [
    ['Rinse the lentils','Rinse lentils in a bowl, changing the water until it is less cloudy. Drain and measure the recipe water.',4,['Lentils'],'Keep the water-to-lentil amount from the recipe so the dal does not become too thin.'],
    ['Simmer until the lentils soften','Add lentils, water and turmeric to a saucepan. Bring to a boil, skim any foam, then simmer partly covered until the lentils mash easily.',20,['Lentils','Turmeric'],'Stir occasionally and add hot water if the pan becomes dry before the lentils soften.'],
    ['Prepare the garlic tadka','In a small pan, warm ghee or oil over medium-low heat. Add cumin and sliced garlic; stir until the garlic turns pale gold.',4,['Cumin','Garlic'],'The garlic continues browning after the heat is off, so remove it before it becomes dark.'],
    ['Soften the tomato in the tempering','Add tomato to the garlic pan and cook until soft and saucy. Keep the heat moderate and stir so the garlic does not burn.',6,['Tomato','Garlic'],'A splash of water helps if the tomato mixture sticks.'],
    ['Combine the tempering and dal','Pour the tomato-garlic mixture into the soft lentils and stir. Simmer gently for a few minutes so the flavors combine.',5,['Tomato','Garlic','Lentils'],'Pour carefully; hot tempering may bubble when it meets the dal.'],
    ['Adjust the texture and serve','Add hot water a little at a time until the dal flows easily from a spoon. Taste for salt and serve warm.',4,['Lentils'],'The dal thickens as it stands, so keep a little hot water nearby.'],
  ],
  'Chicken Curry': [
    ['Prepare the chicken and vegetables','Cut chicken into even pieces and chop onion and tomato. Keep the raw chicken separate from ready-to-eat ingredients and wash hands afterward.',8,['Chicken','Onion','Tomato'],'Set out the ginger and coriander before heating the pan so nothing has to wait in the hot oil.'],
    ['Brown the onion','Heat oil in a heavy pan over medium heat. Add onion and stir often until soft and golden around the edges.',7,['Onion'],'If the edges brown too quickly, lower the heat and add a teaspoon of water.'],
    ['Add ginger and coriander','Stir ginger and coriander into the onion for about 30 seconds, just until fragrant.',2,['Onion','Ginger','Coriander'],'Keep the pan moving so the ground spices do not scorch.'],
    ['Cook down the tomato base','Add tomato and cook, stirring, until it collapses into a thick, pulpy masala with no watery juice around it.',8,['Tomato'],'A thick base clings to the chicken better than raw, watery tomato.'],
    ['Coat and simmer the chicken','Add chicken and turn each piece through the masala. Add the recipe liquid, cover and simmer gently, stirring occasionally, until the thickest piece reaches 74°C/165°F.',20,['Chicken'],'Check temperature in the thickest piece; color alone is not a reliable safety check.'],
    ['Rest and serve the curry','Turn off the heat and let the curry stand covered for 3 minutes. Taste the gravy, adjust salt if needed and serve with rice or flatbread.',3,['Chicken','Tomato'],'If the gravy is too thick, stir in a small splash of hot water.'],
  ],
  'Goan Fish Curry': [
    ['Prepare the fish and curry base','Cut white fish into large, even pieces and pat dry. Blend coconut milk with tamarind, chili and turmeric until smooth.',8,['White fish','Coconut milk','Tamarind','Chili','Turmeric'],'Handle fish with clean utensils and return it to the refrigerator until the sauce is ready.'],
    ['Warm the coconut-tamarind sauce','Pour the blended base into a wide pan over medium-low heat. Stir gently until steaming and just beginning to bubble.',6,['Coconut milk'],'Do not let coconut milk boil hard; gentle heat helps keep the sauce smooth.'],
    ['Taste the sauce before adding fish','Let the sauce simmer quietly for a few minutes, then taste for salt and tang. Adjust only with seasonings included in the recipe.',4,['Tamarind','Chili'],'The fish cooks quickly, so balance the sauce before adding it.'],
    ['Poach the fish gently','Lay fish pieces in one layer in the simmering sauce. Spoon sauce over the top and cook gently, turning once if needed, until opaque and flaking.',10,['White fish'],'Avoid stirring hard; delicate fish can break apart. Cook to 63°C/145°F where a thermometer is available.'],
    ['Rest briefly and serve','Turn off the heat and leave the fish in the sauce for 2 minutes. Serve carefully with rice while the pieces are still intact.',2,['White fish','Coconut milk'],'Lift fish with a broad spoon rather than stirring it through the sauce.'],
  ],
  'Mutton Rogan Josh': [
    ['Dry and portion the lamb','Pat lamb dry and cut into even pieces. Measure yogurt, chili, fennel and ginger before heating the pot.',8,['Lamb','Yogurt','Kashmiri chili','Fennel','Ginger'],'Dry meat browns; wet surfaces steam instead.'],
    ['Brown the lamb in batches','Heat a heavy pot over medium-high heat with the recipe oil. Brown lamb on several sides in uncrowded batches, transferring each batch to a plate.',15,['Lamb'],'Let the pot recover its heat between batches so the meat sears instead of releasing water.'],
    ['Lower the heat and bloom the spices','Reduce to medium-low. Add Kashmiri chili, fennel and ginger, stirring briefly until fragrant without letting the chili darken.',3,['Kashmiri chili','Fennel','Ginger'],'Ground chili burns quickly; keep it moving and reduce heat if it smells sharp.'],
    ['Stir in the yogurt gradually','Add yogurt a spoonful at a time while stirring, keeping the heat low so it blends into the spiced base instead of curdling.',7,['Yogurt'],'Room-temperature yogurt is less likely to seize in the hot pot.'],
    ['Braise until the lamb is fork-tender','Return lamb and juices to the pot. Add the recipe liquid, cover and cook at a gentle simmer, stirring now and then, until a fork enters the meat easily.',60,['Lamb'],'Add hot water if the pot becomes dry before the lamb is tender.'],
    ['Rest and finish the curry','Turn off the heat and rest covered for 5 minutes. Skim excess fat if desired, taste for salt and serve with rice or flatbread.',5,['Lamb'],'A long gentle braise tenderizes the lamb; avoid raising the heat to rush it.'],
  ],
  'Chicken 65': [
    ['Cut and season the chicken','Cut chicken into even bite-sized pieces. Mix with yogurt, chili and rice flour until each piece has a thin, even coating.',8,['Chicken','Yogurt','Chili','Rice flour'],'Keep the coating light; thick clumps can stay doughy when fried.'],
    ['Rest the coating','Cover the bowl and rest the chicken while you prepare the pan and curry leaves. Keep it chilled if the room is warm or the wait is longer.',8,['Chicken','Yogurt','Curry leaves'],'Do not leave raw chicken at room temperature for an extended period.'],
    ['Shallow-fry in small batches','Heat a shallow layer of oil over medium heat. Add chicken without crowding and turn pieces until crisp and browned on all sides.',12,['Chicken'],'If the coating browns too fast, lower the heat so the center can cook safely.'],
    ['Check doneness and drain','Check the thickest chicken piece reaches 74°C/165°F, then transfer pieces to a rack or paper-lined plate to drain.',4,['Chicken'],'Use a clean thermometer and plate; do not reuse raw-chicken utensils.'],
    ['Temper the curry leaves and chili','In a clean pan, warm a small amount of oil over medium-low heat. Add curry leaves and chili carefully and stir just until fragrant.',3,['Curry leaves','Chili'],'Fresh curry leaves may splutter when they meet hot oil.'],
    ['Toss and serve while crisp','Add fried chicken to the tempering and toss briefly to coat. Turn off the heat and serve immediately.',2,['Chicken','Curry leaves','Chili'],'A long rest in sauce softens the crisp coating.'],
  ],
  'Paneer Butter Masala': [
    ['Cut and lightly sear paneer','Cut paneer into bite-sized cubes. Warm a little oil over medium heat and turn the cubes until lightly golden; transfer to a plate.',5,['Paneer'],'Sear briefly so the center stays soft.'],
    ['Soften the tomato and cashews','Simmer tomato and cashews with a little water until both are very soft. The cashews should crush easily with a spoon.',10,['Tomato','Cashews'],'Add water if the saucepan starts drying before the cashews soften.'],
    ['Blend the sauce carefully','Let the hot mixture cool slightly, then blend until smooth. Open the blender vent carefully and cover it with a towel to release steam.',4,['Tomato','Cashews'],'Never seal very hot liquid in a blender jar.'],
    ['Cook the butter and spice base','Melt butter in a pan over low heat and stir in the recipe spices until fragrant. Pour in the blended tomato mixture carefully.',5,['Butter','Tomato'],'Low heat prevents milk solids in butter and the spices from burning.'],
    ['Simmer and enrich the gravy','Simmer gently until the gravy thickens enough to coat a spoon. Stir in cream and lower the heat.',10,['Cream'],'If the sauce becomes too thick, loosen it with a spoonful of water.'],
    ['Warm paneer through and serve','Fold paneer into the gravy and warm for 2–3 minutes without a hard boil. Taste for salt and serve with rice or flatbread.',6,['Paneer','Cream'],'Boiling hard after adding cream can make the sauce split.'],
  ],
  'Pasta Alfredo': [
    ['Bring the pasta water to a boil','Fill a large pot with water and bring it to a rolling boil. Salt the water, then add pasta and stir during the first minute.',5,['Pasta'],'Use a pot large enough for pasta to move freely.'],
    ['Cook and reserve pasta water','Cook pasta until just tender with a slight bite, following the package timing. Before draining, reserve a mug of the starchy water.',10,['Pasta'],'The pasta will finish in the sauce, so avoid overcooking it in the pot.'],
    ['Warm butter and cream gently','Melt butter in a wide pan over low heat. Add cream and warm until steaming; do not let it boil vigorously.',5,['Butter','Cream'],'A gentle heat keeps the dairy smooth.'],
    ['Toss pasta with the sauce','Add drained pasta and parmesan. Toss continuously over low heat until coated; add reserved pasta water a splash at a time for a silky sauce.',5,['Pasta','Parmesan'],'The sauce should cling to the pasta, not pool at the bottom.'],
    ['Season and serve immediately','Add black pepper and taste before adding salt. Turn off the heat and serve while the sauce is glossy.',3,['Black pepper','Parmesan'],'Cream sauces thicken as they cool; loosen with a little reserved water if needed.'],
  ],
  'Vegetable Lasagna': [
    ['Prepare the vegetables and oven','Heat the oven to 190°C/375°F. Cut zucchini evenly and sauté or roast until tender and excess moisture has evaporated.',15,['Zucchini'],'Removing extra moisture helps prevent watery slices.'],
    ['Warm the tomato sauce and prepare the dish','Warm tomato sauce so it spreads easily. Lightly coat the baking dish with sauce before layering.',5,['Tomato'],'A thin sauce layer prevents the bottom pasta sheets sticking.'],
    ['Build the first layers','Add lasagna sheets, vegetables and ricotta in even layers. Spread each filling close to the edges without overloading.',10,['Lasagna sheets','Zucchini','Ricotta'],'Keep layers even so pasta cooks at the same rate.'],
    ['Finish layering with cheese','Repeat the pasta and filling layers, then finish with tomato sauce and mozzarella across the top.',8,['Lasagna sheets','Tomato','Mozzarella'],'Cover dry pasta corners with sauce so they soften in the oven.'],
    ['Bake covered, then brown the top','Cover the dish and bake until the sheets are tender. Uncover near the end and bake until mozzarella is melted and bubbling.',32,['Lasagna sheets','Mozzarella'],'If the top browns before the pasta is tender, cover it loosely again.'],
    ['Rest before slicing','Remove carefully from the oven and rest until the bubbling settles and the layers hold together when cut.',8,['Mozzarella'],'Use oven mitts and a stable heat-safe surface.'],
  ],
  'Veg Fried Rice': [
    ['Prepare everything before heating','Dice carrot evenly; measure peas, cold cooked rice and soy sauce. Break up rice clumps with clean fingers or a fork.',8,['Carrot','Peas','Rice','Soy sauce'],'Use chilled cooked rice for separate grains; cool leftovers promptly and refrigerate.'],
    ['Scramble the eggs','Heat a wok over medium-high heat, add a little oil and pour in beaten eggs. Stir until softly set, then move to a clean plate.',3,['Eggs'],'Remove the eggs before they dry; they will warm again at the end.'],
    ['Stir-fry the carrot and peas','Add a little more oil, then carrot and peas. Toss frequently over high heat until bright and crisp-tender.',4,['Carrot','Peas'],'Keep ingredients moving in the hot pan to prevent scorching.'],
    ['Heat and separate the rice','Add cold rice and break up remaining clumps with the spatula. Spread it briefly against the pan so it heats, then toss.',4,['Rice'],'Do not add wet rice; excess water makes fried rice soft and sticky.'],
    ['Season and return the egg','Return cooked egg to the wok and add soy sauce around the hot pan edge. Toss until everything is steaming hot.',3,['Eggs','Soy sauce'],'Taste before adding salt because soy sauce is already salty.'],
    ['Finish and serve','Turn off the heat, toss once more and serve immediately while the rice is hot and the vegetables still have a little bite.',2,['Rice','Carrot','Peas'],'If making a larger batch, fry in batches instead of crowding the wok.'],
  ],
  'Pad Thai': [
    ['Soak the rice noodles','Cover rice noodles with warm water and soak until pliable but still slightly firm in the center. Drain well.',10,['Rice noodles'],'Do not fully soften them in the bowl; they finish cooking in the pan.'],
    ['Mix the sauce and prepare tofu','Stir tamarind and the recipe seasonings together. Pat tofu dry and cut into small, even pieces.',5,['Tamarind','Tofu'],'Dry tofu browns more readily and splatters less.'],
    ['Sear tofu until golden','Heat a wide pan over medium-high heat with a little oil. Add tofu in one layer and turn until the sides are lightly golden.',5,['Tofu'],'Give tofu space; overcrowding makes it steam.'],
    ['Toss noodles with sauce','Add drained noodles and sauce. Toss continuously, adding small splashes of water only if the noodles remain firm or the pan looks dry.',6,['Rice noodles','Tamarind'],'The noodles should become tender and coated, not swimming in sauce.'],
    ['Cook the egg and combine','Push noodles aside. Add egg to the clear part of the pan and stir until set, then fold it through the noodles.',3,['Eggs','Rice noodles'],'Keep the egg moving so it cooks fully without forming a large dry sheet.'],
    ['Add peanuts and serve','Turn off the heat and fold through peanuts. Taste the balance, then serve promptly while the noodles are springy.',4,['Peanuts','Tamarind'],'Add peanuts at the end to preserve some crunch.'],
  ],
  'Bibimbap': [
    ['Cook the rice','Rinse rice until the water is mostly clear, then cook with the recipe-measured water until tender. Keep covered off the heat.',15,['Rice'],'Let the rice rest covered for 5 minutes so moisture evens out.'],
    ['Cut and sort the vegetables','Slice carrot and prepare spinach into separate piles. Keep cuts thin and similar so each topping cooks quickly.',7,['Carrot','Spinach'],'Cooking vegetables separately helps preserve their colors and textures.'],
    ['Cook the carrot topping','Warm a little oil in a skillet over medium heat and sauté carrot, stirring until softened but still bright.',4,['Carrot'],'Add a small splash of water if the pan dries before the carrot softens.'],
    ['Wilt and season the spinach','Add spinach to a clean warm pan and turn until just wilted. Remove from heat and season using the ingredients listed in the recipe.',3,['Spinach'],'Do not overcook spinach; it should stay green rather than grey.'],
    ['Cook the egg safely','Heat a little oil and cook the egg until the white is set. For a fully cooked egg, cover briefly until the yolk reaches your preference.',4,['Eggs'],'Use a clean plate for the cooked egg.'],
    ['Arrange the bowls and finish','Divide rice between bowls. Arrange carrot and spinach on top, add the egg and a small amount of gochujang, then mix just before eating.',4,['Rice','Carrot','Spinach','Eggs','Gochujang'],'Start with less gochujang and add more at the table if desired.'],
  ],
  'Mushroom Risotto': [
    ['Warm the stock and slice mushrooms','Warm stock in a small saucepan and keep it barely simmering. Slice mushrooms evenly while it heats.',5,['Stock','Mushrooms'],'Warm stock blends into the rice more smoothly than cold liquid.'],
    ['Brown the mushrooms','Sauté mushrooms in butter over medium-high heat until browned and their released liquid has evaporated. Set aside.',8,['Mushrooms','Butter'],'Let mushrooms sit briefly between stirs so they brown rather than steam.'],
    ['Toast the arborio rice','Add arborio rice to the pot and stir over medium heat until the outside looks slightly translucent and the grains smell nutty.',3,['Arborio rice'],'Keep stirring so the rice does not brown on the bottom.'],
    ['Add stock gradually','Add one ladle of warm stock and stir until mostly absorbed before adding the next. Maintain a gentle simmer and repeat until rice is nearly tender.',22,['Arborio rice','Stock'],'The rice should remain loose and gently bubbling; lower heat if it sticks.'],
    ['Finish with mushrooms and parmesan','Stir browned mushrooms and parmesan into the rice. Cook until the rice is tender with a slight bite and the mixture flows slowly from a spoon.',5,['Mushrooms','Parmesan'],'Add a final splash of stock if the risotto becomes stiff.'],
    ['Rest and serve the risotto','Turn off the heat, fold in butter if listed and rest for 1 minute. Taste, then serve while creamy.',2,['Butter','Parmesan'],'Risotto firms quickly as it stands; serve promptly.'],
  ],
  'Paneer Tikka': [
    ['Cut paneer and pepper evenly','Cut paneer and bell pepper into similar-sized cubes. Pat paneer dry so the marinade clings instead of sliding off.',5,['Paneer','Bell pepper'],'Keep the pieces large enough to turn without breaking.'],
    ['Mix the yogurt marinade','Stir yogurt, tikka masala and lemon juice together until smooth and evenly colored.',3,['Yogurt','Tikka masala','Lemon'],'Taste a tiny amount before adding paneer; spice mixes vary in salt and heat.'],
    ['Coat and rest the pieces','Fold paneer and pepper through the marinade until coated on all sides. Rest for at least 10 minutes while the pan or grill heats.',10,['Paneer','Bell pepper','Yogurt'],'Thread loosely if using skewers so heat can reach between pieces.'],
    ['Heat the pan or grill','Heat a grill pan or heavy skillet over medium-high heat. Brush lightly with oil only if it is listed or available.',3,['Paneer'],'A properly hot pan gives char marks before the paneer dries.'],
    ['Char the paneer and pepper','Cook in a single layer, turning carefully every few minutes, until pepper softens and paneer edges show golden-brown spots.',10,['Paneer','Bell pepper'],'If the marinade darkens too quickly, lower heat to medium.'],
    ['Finish with lemon and serve','Move the tikka to a plate, squeeze over the listed lemon and serve while warm and tender.',4,['Lemon'],'Paneer firms as it cools; serve soon after cooking.'],
  ],
  'Chole': [
    ['Drain and rinse the chickpeas','Drain soaked chickpeas and rinse under fresh water. If using cooked chickpeas, keep a little cooking liquid for loosening the curry.',4,['Chickpeas'],'Dried chickpeas must be fully cooked before they go into the masala.'],
    ['Soften the onion','Heat a heavy pan over medium heat with listed oil if available. Add chopped onion and cook, stirring often, until soft and golden.',8,['Onion'],'Lower heat if the edges brown before the center softens.'],
    ['Cook ginger and chole masala','Add ginger and chole masala to the onion. Stir for about 30 seconds until fragrant, keeping the spices moving.',3,['Onion','Ginger','Chole masala'],'If the mixture looks dry, add a teaspoon of water rather than letting the spices scorch.'],
    ['Break down the tomato','Add chopped tomato and cook until it collapses into a thick masala with no watery juice around the edges.',8,['Tomato'],'Press larger tomato pieces against the pan with the spoon to help them soften.'],
    ['Simmer chickpeas in the masala','Stir in chickpeas and enough reserved liquid to make a thick sauce. Cover partly and simmer gently, stirring now and then.',15,['Chickpeas'],'Mash a few chickpeas against the pan to thicken the curry naturally.'],
    ['Taste and serve the chole','Taste for seasoning and check that the chickpeas are soft throughout. Turn off the heat and serve warm with a suitable side.',3,['Chickpeas'],'If the curry thickens while standing, loosen it with a splash of hot water.'],
  ],
  'Aloo Paratha': [
    ['Mix and rest the dough','Add water gradually to whole wheat flour and knead until a soft, smooth dough forms. Cover and rest while preparing the filling.',10,['Whole wheat flour'],'The dough should feel pliable, not sticky; add water a little at a time.'],
    ['Cook and mash the potatoes','Boil potatoes until a fork slides into the center easily. Drain, cool enough to handle, peel and mash until no large hard pieces remain.',12,['Potato'],'Dry the potatoes well after boiling so the filling does not make the dough wet.'],
    ['Season the filling','Mix mashed potato with coriander and finely chopped green chili. Taste carefully and distribute the seasoning evenly.',4,['Potato','Coriander','Green chili'],'Keep the filling fairly dry; wet filling can tear the paratha.'],
    ['Fill and seal the dough','Divide dough into portions and roll each into a small round. Place filling in the center, gather the edges and pinch closed.',8,['Whole wheat flour','Potato'],'Seal any gaps before rolling so the filling stays inside.'],
    ['Roll the stuffed paratha gently','Dust lightly with flour and roll from the center outward into an even round, turning as needed without pressing too hard.',5,['Whole wheat flour'],'If filling breaks through, patch with a pinch of dough and use less pressure.'],
    ['Griddle until golden','Heat a skillet over medium heat. Cook each paratha, turning when bubbles appear; brush with butter and cook both sides until golden spots form.',12,['Butter'],'The pan should sizzle gently; reduce heat if the outside darkens before the center cooks.'],
  ],
  'Poha': [
    ['Rinse and drain the poha','Place poha in a sieve and rinse briefly under cool water until just softened. Shake off excess water and leave it to drain.',4,['Poha'],'Do not soak it in a bowl; oversoft flakes can turn mushy in the pan.'],
    ['Prepare the onion and tempering','Chop onion evenly. Heat oil in a skillet over medium heat, add mustard seeds and wait until they begin to pop.',4,['Onion'],'Use a lid briefly if mustard seeds jump out of the pan.'],
    ['Soften onion and curry leaves','Add curry leaves and onion carefully. Stir and cook until the onion is translucent and soft, not deeply browned.',5,['Onion','Curry leaves'],'If onion browns too fast, lower the heat before adding the poha.'],
    ['Toast peanuts and turmeric','Add peanuts and turmeric and stir until the peanuts smell toasted and the turmeric coats the onion evenly.',3,['Peanuts','Turmeric','Onion'],'Keep stirring so turmeric does not sit on the hot pan and scorch.'],
    ['Fold in the poha','Add drained poha and fold gently until evenly colored. Cover over low heat for a few minutes until hot throughout.',5,['Poha'],'Use a wide spatula and lift rather than stir hard to keep flakes intact.'],
    ['Finish with lemon and serve','Turn off the heat, add lemon juice and fluff lightly. Taste, then serve while warm.',3,['Lemon'],'Add lemon after the heat is off to keep its fresh, bright flavor.'],
  ],
  'Egg Curry': [
    ['Boil the eggs','Place eggs in a saucepan, cover with water and bring to a boil. Lower to a steady simmer until the centers are set.',10,['Eggs'],'Use a spoon to lower eggs gently and avoid cracking the shells.'],
    ['Cool, peel and halve the eggs','Move eggs into cool water until safe to handle. Tap and peel the shells, then halve lengthwise with a clean knife.',5,['Eggs'],'Cooling makes peeling easier and protects your fingers.'],
    ['Soften the onion','Heat oil in a pan over medium heat and cook chopped onion, stirring regularly, until golden and soft.',8,['Onion'],'A patient medium heat gives sweetness without burnt edges.'],
    ['Bloom ginger and garam masala','Reduce heat to medium-low. Stir in ginger and garam masala for about 30 seconds until fragrant.',3,['Ginger','Garam masala'],'Do not let the ground spice smoke or darken quickly.'],
    ['Cook the tomato into a gravy','Add tomato and cook, stirring, until it breaks down into a thick sauce. Add a small splash of water if it sticks.',8,['Tomato'],'The base is ready when it looks pulpy rather than watery.'],
    ['Warm the eggs in the curry','Add enough water to loosen the gravy, then place egg halves cut-side up. Simmer gently for a few minutes and spoon sauce over them.',6,['Eggs'],'Avoid vigorous stirring so the eggs keep their shape.'],
  ],
  'Pav Bhaji': [
    ['Cut and boil the vegetables','Cut potato and cauliflower into even chunks. Simmer them with peas until a fork slides through the largest piece easily.',15,['Potato','Cauliflower','Peas'],'Cut potato and cauliflower to similar sizes so they finish together.'],
    ['Drain and mash the vegetables','Drain excess water, reserving a little in case the mixture needs loosening. Mash vegetables to a chunky texture.',5,['Potato','Cauliflower','Peas'],'Leave a few small pieces for texture instead of making a smooth puree.'],
    ['Soften the tomato in butter','Melt butter in a wide pan over medium heat. Add tomato and cook, stirring, until very soft and saucy.',7,['Tomato','Butter'],'Lower the heat if the butter browns before the tomato softens.'],
    ['Toast the pav bhaji masala','Stir pav bhaji masala into the tomato base for 20–30 seconds until fragrant.',2,['Pav bhaji masala','Tomato'],'Keep the spice moving; it should smell toasted, never burnt.'],
    ['Combine and simmer the bhaji','Add mashed vegetables and stir until evenly coated. Simmer gently, mashing and stirring until thick and hot throughout.',10,['Potato','Cauliflower','Peas'],'Add a spoonful of reserved vegetable water if the bhaji becomes too stiff.'],
    ['Toast the pav and serve','Split the rolls and toast cut sides in butter in a clean skillet until golden. Serve beside the bhaji while warm.',5,['Pav bhaji masala','Butter'],'Toast rolls just before serving so they stay crisp outside and soft inside.'],
  ],
  'Idli Sambar': [
    ['Rinse and start the lentils','Rinse lentils until the water runs less cloudy. Add fresh water in a saucepan and cook until the grains are soft enough to mash.',20,['Lentils'],'Use a separate pot or pressure cooker if that is how the supplied lentils are normally cooked.'],
    ['Cut the sambar vegetables','Rinse carrot and drumstick and cut into similar-sized pieces. Keep the pieces ready while the lentils finish.',7,['Carrot','Drumstick','Lentils'],'Cut drumstick into short lengths that fit easily in a spoon.'],
    ['Simmer vegetables with the lentils','Add vegetables and sambar spices to the soft lentils with enough water for a spoonable stew. Simmer until vegetables are tender.',18,['Lentils','Carrot','Drumstick','Sambar spices'],'A fork should enter the carrot easily while it still holds its shape.'],
    ['Prepare the idli steamer','Bring water in the steamer to a steady boil. Lightly grease the molds and pour fermented idli batter into each cavity without filling to the rim.',5,['Rice','Urad dal'],'Leave space for the batter to rise as it steams.'],
    ['Steam the idlis','Place molds in the steamer and cook covered until the idlis are set and a clean tester comes out without wet batter.',12,['Rice','Urad dal'],'Avoid opening the lid repeatedly; lost steam delays cooking.'],
    ['Rest and serve together','Turn off the heat and rest idlis briefly before unmolding. Ladle hot sambar alongside the soft cakes.',3,['Rice','Lentils'],'Use a damp spoon to release idlis cleanly from the molds.'],
  ],
  'Lemon Rice': [
    ['Cook and cool the rice','Cook rice until tender but separate. Spread it briefly on a wide plate so excess steam escapes and the grains do not clump.',12,['Rice'],'Cool the rice slightly before mixing so it stays whole.'],
    ['Heat the oil and mustard seeds','Warm oil in a pan over medium heat. Add mustard seeds and wait until they begin popping.',2,['Mustard seeds'],'Stand back and keep a lid nearby if seeds jump from the pan.'],
    ['Toast the peanuts and curry leaves','Add peanuts, curry leaves and turmeric carefully. Stir until peanuts smell toasted and the leaves are fragrant.',4,['Peanuts','Curry leaves','Turmeric'],'Add curry leaves gently because damp leaves can splutter in hot oil.'],
    ['Fold in the rice','Turn off the heat, add lemon juice and cooked rice, then fold gently until the yellow tempering is distributed.',4,['Lemon','Rice'],'Add lemon off the heat for a fresher taste.'],
    ['Taste and serve','Taste a few grains and adjust only with listed seasonings. Serve warm or at room temperature.',3,['Lemon','Rice'],'If the rice feels dry, fold in a teaspoon of water or listed oil at a time.'],
  ],
  'Margherita Pizza': [
    ['Heat the oven and tray','Heat the oven to 240°C/475°F or its highest safe setting. Place a heavy tray or pizza stone inside to preheat.',10,['Pizza dough'],'Use oven mitts when handling the hot tray or stone.'],
    ['Shape the dough','Lightly flour the work surface if available. Stretch pizza dough into a round, keeping a slightly thicker edge for the crust.',6,['Pizza dough'],'If the dough springs back, rest it for a few minutes before stretching again.'],
    ['Add tomato and mozzarella','Spread a thin layer of tomato over the dough, leaving the edge clear. Tear or slice mozzarella and distribute it evenly.',4,['Tomato','Mozzarella'],'Too much sauce can make the center soggy, so keep the layer thin.'],
    ['Bake until the crust is browned','Transfer the topped dough to the hot tray and bake until the crust has browned spots and mozzarella is bubbling.',8,['Pizza dough','Mozzarella'],'Ovens vary; check early and rotate once if one side browns faster.'],
    ['Finish with basil and oil','Scatter basil over the hot pizza and add olive oil if listed. Rest briefly, slice carefully and serve.',2,['Basil','Olive oil'],'Basil added after baking stays fragrant and bright.'],
  ],
  'Chicken Tacos': [
    ['Prepare the chicken and toppings','Pat chicken dry and coat with paprika and listed oil. Slice avocado and prepare lime; keep raw chicken separate from ready-to-eat toppings.',8,['Chicken','Paprika','Avocado','Lime'],'Wash hands and the cutting board after handling raw chicken.'],
    ['Heat the skillet','Warm a heavy skillet over medium-high heat until hot. Add the seasoned chicken in one layer.',2,['Chicken'],'A hot pan helps the chicken brown instead of releasing juices and steaming.'],
    ['Cook the chicken through','Sear chicken, turning once, until browned and the thickest part reaches 74°C/165°F.',12,['Chicken'],'Use a clean thermometer rather than judging doneness by color alone.'],
    ['Rest and slice the chicken','Move chicken to a clean board and rest briefly. Slice across the grain into strips so each bite stays tender.',4,['Chicken'],'Resting keeps more juice in the meat when you slice it.'],
    ['Warm the tortillas','Warm tortillas in a dry skillet until flexible and lightly toasted. Stack under a clean towel.',3,['Tortillas'],'Do not leave them in the pan until crisp; they should fold without cracking.'],
    ['Assemble with avocado and lime','Fill each tortilla with chicken and avocado. Squeeze lime over the top and serve while the tortillas are warm.',3,['Tortillas','Chicken','Avocado','Lime'],'Add lime gradually and taste so it brightens without overpowering the filling.'],
  ],
  'Shakshuka': [
    ['Prepare the vegetables','Rinse bell pepper and tomato. Dice them evenly and chop onion so they soften at the same rate.',7,['Bell pepper','Tomato','Onion'],'Smaller pieces make the sauce easier to scoop with bread.'],
    ['Soften the onion and pepper','Heat a wide lidded skillet over medium heat. Add listed oil if available, then cook onion and pepper, stirring, until soft.',8,['Onion','Bell pepper'],'If the vegetables start browning before softening, lower the heat.'],
    ['Cook the tomato and paprika','Add tomato and paprika. Stir and simmer until the tomato collapses into a thick sauce with gentle bubbles.',10,['Tomato','Paprika'],'Press larger tomato pieces against the pan to help them break down.'],
    ['Make spaces and add the eggs','Lower the heat and make a shallow well in the sauce for each egg. Crack eggs into the wells without breaking the yolks.',3,['Eggs'],'Crack each egg into a small cup first if you want to remove shell fragments easily.'],
    ['Cover and poach the eggs','Cover the skillet and cook gently until the whites are set and yolks reach your preferred doneness.',6,['Eggs'],'Check after a few minutes; residual heat continues cooking the eggs after the pan is removed.'],
    ['Rest and serve from the skillet','Turn off the heat, uncover carefully and serve the sauce and eggs warm from the pan.',2,['Eggs','Tomato'],'Lift the lid away from you so trapped steam does not reach your face.'],
  ],
  'Falafel Bowl': [
    ['Drain and dry the chickpeas','Drain soaked chickpeas thoroughly and pat dry. Remove loose skins only if they come away easily.',5,['Chickpeas'],'Dry chickpeas help the mixture hold together and crisp in the pan.'],
    ['Pulse the falafel mixture','Pulse chickpeas with parsley and cumin until coarse and crumbly, stopping before the mixture becomes a smooth paste.',5,['Chickpeas','Parsley','Cumin'],'The mixture should hold when pressed but still show small chickpea pieces.'],
    ['Shape and chill the patties','Form small, even patties and set them on a plate. Chill briefly while preparing the bowl ingredients.',10,['Chickpeas'],'If a patty crumbles, press it firmly and chill longer before cooking.'],
    ['Pan-fry until crisp','Heat a thin layer of oil over medium heat. Cook patties in batches, turning once their first side is browned and releases easily.',12,['Chickpeas'],'Do not move patties too soon; the crust helps them hold their shape.'],
    ['Prepare the bowl and tahini','Slice cucumber. Stir tahini with small splashes of water until smooth and pourable.',6,['Cucumber','Tahini'],'Add water gradually; tahini can seize before loosening into a creamy dressing.'],
    ['Assemble and serve','Arrange cucumber and any listed greens or grains in bowls. Add warm falafel and drizzle with tahini.',4,['Tahini','Cucumber'],'Add dressing just before eating to keep the falafel crisp.'],
  ],
  'Grilled Salmon': [
    ['Dry and season the salmon','Pat salmon dry and season with black pepper, lemon and olive oil from the ingredient list. Let it stand while the grill heats.',5,['Salmon','Lemon','Olive oil','Black pepper'],'Dry skin or surface browns more readily and is less likely to stick.'],
    ['Preheat the grill or pan','Heat a grill or grill pan over medium-high heat until hot. Clean and lightly oil the grate only if oil is listed or available.',5,['Olive oil'],'A hot, clean surface helps fish release instead of tearing.'],
    ['Cook the first side without moving','Place salmon skin-side down if it has skin. Cook until the lower edge turns opaque and the fish releases with a gentle lift.',6,['Salmon'],'If it sticks, give it another minute rather than pulling it off the grill.'],
    ['Turn and finish cooking','Turn carefully and cook until the thickest part is opaque and flakes, or reaches 63°C/145°F on a clean thermometer.',6,['Salmon'],'Use a thin spatula and support the whole fillet while turning.'],
    ['Rest and add lemon','Move salmon to a clean plate and rest briefly. Add dill and another squeeze of lemon from the listed ingredients.',3,['Salmon','Dill','Lemon'],'A short rest finishes the center without drying the edges.'],
  ],
  'Chicken Noodle Soup': [
    ['Cut the vegetables and heat stock','Cut carrot and celery into small, even pieces. Pour stock into a large pot and bring it to a gentle simmer.',8,['Carrot','Celery','Stock'],'Keep the pieces similar in size so they soften together.'],
    ['Simmer the chicken safely','Add chicken to the stock and simmer gently until the thickest piece reaches 74°C/165°F. Lift it to a clean plate.',20,['Chicken','Stock'],'Avoid a hard boil, which can make chicken tough and cloud the broth.'],
    ['Shred the chicken','When cool enough to handle, shred chicken with two clean forks into bite-sized pieces.',5,['Chicken'],'Do not use the plate or utensils that held raw chicken.'],
    ['Cook vegetables and noodles','Add carrot and celery to the broth and simmer until nearly tender. Add egg noodles and cook to package timing.',12,['Carrot','Celery','Egg noodles'],'Add noodles only when the vegetables are nearly tender so they do not overcook.'],
    ['Return chicken and season','Return shredded chicken to the pot and warm until steaming. Taste the broth and season only with listed ingredients.',4,['Chicken'],'If noodles absorb too much broth, add hot water or stock if it is listed.'],
    ['Serve the soup hot','Turn off the heat and ladle into bowls. Cool leftovers promptly and refrigerate in a covered container.',3,['Chicken','Egg noodles'],'Reheat leftovers until steaming hot throughout.'],
  ],
};

const amounts: Record<string, [number | null, string]> = {
  'Basmati rice':[1,'cup'],'Rice':[1,'cup'],'Urad dal':[0.25,'cup'],'Potato':[2,'pieces'],'Mustard seeds':[0.5,'tsp'],'Curry leaves':[8,'leaves'],
  'Chicken':[300,'g'],'Lamb':[400,'g'],'White fish':[300,'g'],'Salmon':[300,'g'],'Paneer':[250,'g'],'Yogurt':[0.5,'cup'],'Cream':[0.25,'cup'],'Butter':[2,'tbsp'],'Tomato':[2,'pieces'],'Onion':[1,'piece'],'Garlic':[3,'cloves'],'Ginger':[1,'tbsp'],'Garam masala':[1,'tsp'],'Coconut milk':[1,'cup'],'Tamarind':[1,'tbsp'],'Chili':[1,'piece'],'Turmeric':[0.5,'tsp'],'Chickpeas':[1.5,'cups'],'Kidney beans':[1,'cup'],'Peas':[0.5,'cup'],'Carrot':[1,'piece'],'Green beans':[0.5,'cup'],'Lentils':[0.75,'cup'],'Eggs':[2,'pieces'],'Whole wheat flour':[1.5,'cups'],'Coriander':[2,'tbsp'],'Green chili':[1,'piece'],'Poha':[1.5,'cups'],'Peanuts':[2,'tbsp'],'Lemon':[1,'piece'],'Cauliflower':[1,'cup'],'Drumstick':[1,'piece'],'Cashews':[0.25,'cup'],'Pizza dough':[250,'g'],'Mozzarella':[100,'g'],'Basil':[6,'leaves'],'Olive oil':[1,'tbsp'],'Pasta':[200,'g'],'Parmesan':[0.25,'cup'],'Black pepper':[0.25,'tsp'],'Lasagna sheets':[6,'sheets'],'Zucchini':[1,'piece'],'Ricotta':[0.5,'cup'],'Tortillas':[4,'pieces'],'Avocado':[1,'piece'],'Lime':[1,'piece'],'Paprika':[1,'tsp'],'Black beans':[1,'can'],'Tomato sauce':[1,'cup'],'Cheddar':[1,'cup'],'Corn':[0.5,'cup'],'Soy sauce':[1,'tbsp'],'Rice noodles':[150,'g'],'Tofu':[150,'g'],'Cucumber':[1,'piece'],'Feta':[75,'g'],'Olives':[0.25,'cup'],'Bell pepper':[1,'piece'],'Tahini':[2,'tbsp'],'Parsley':[0.25,'cup'],'Macaroni':[200,'g'],'Milk':[1,'cup'],'Dill':[1,'tbsp'],'Arborio rice':[1,'cup'],'Mushrooms':[200,'g'],'Stock':[3,'cups'],'Egg noodles':[150,'g'],'Celery':[2,'stalks'],'Mango':[1,'cup'],'Cardamom':[0.25,'tsp'],'Honey':[1,'tbsp'],
  'Tikka masala':[1,'tbsp'],'Chole masala':[1,'tbsp'],'Kashmiri chili':[1,'tsp'],'Fennel':[1,'tsp'],'Rice flour':[2,'tbsp'],'Pav bhaji masala':[1,'tbsp'],'Pav rolls':[2,'pieces'],'Mustard':[0.5,'tsp'],'Gochujang':[1,'tbsp'],'Sambar spices':[1,'tbsp'],'Spices':[1,'tsp'],'Salt':[0.5,'tsp'],'Oil':[2,'tbsp'],'Cumin':[1,'tsp'],'Spinach':[200,'g']
};

export function getPreparationSteps(recipe: Recipe): PreparationStep[] {
  const seeds = expandedPreparations[recipe.title] ?? preparations[recipe.title];
  const ingredientNames = new Map(recipe.ingredients.map(name => [name.trim().toLocaleLowerCase(), name.trim()]));
  const matchIngredient = (name: string) => ingredientNames.get(name.trim().toLocaleLowerCase());
  const normalize = (steps: PreparationStep[]) => {
    const safe = steps.map(step => ({
      ...step,
      durationMinutes: Number.isFinite(step.durationMinutes) ? Math.max(1, Math.round(step.durationMinutes)) : 1,
      ingredients: [...new Set((step.ingredients || []).map(matchIngredient).filter((name): name is string => Boolean(name)))],
      tip: step.tip?.trim() || tipForStep(recipe, step.title, step.description),
    }));
    const target = Number.isFinite(recipe.minutes) && recipe.minutes >= safe.length ? Math.round(recipe.minutes) : 0;
    const current = safe.reduce((sum, step) => sum + step.durationMinutes, 0);
    if (target && current && Math.abs(target - current) / current > 0.05) {
      let remaining = target;
      safe.forEach((step, index) => {
        const durationMinutes = index === safe.length - 1 ? Math.max(1, remaining) : Math.max(1, Math.round(step.durationMinutes * target / current));
        step.durationMinutes = durationMinutes;
        remaining -= durationMinutes;
      });
    }
    return safe.map((step, index) => ({...step, stepNumber:index+1}));
  };
  if (seeds) return normalize(seeds.map(([title, description, durationMinutes, ingredients, tip]) => ({title, description, durationMinutes, ingredients, tip})));
  if (recipe.preparationSteps?.length) return normalize(recipe.preparationSteps);
  const legacy = Array.isArray(recipe.steps) ? recipe.steps.filter(Boolean) : [];
  const total = Math.max(1, recipe.minutes || 1);
  return normalize(legacy.map((description, index) => ({
    title: titleFromInstruction(description, index), description,
    durationMinutes: Math.max(1, Math.round(total / Math.max(1, legacy.length))),
    ingredients: recipe.ingredients.filter(name => description.toLowerCase().includes(name.toLowerCase())),
  })));
}

function tipForStep(recipe: Recipe, title: string, description: string): string | undefined {
  const text = `${title} ${description}`.toLowerCase();
  if (/chicken|turkey|poultry/.test(text)) return 'For food safety, check the thickest piece reaches 74°C/165°F with a clean thermometer.';
  if (/fish|salmon|seafood|poach/.test(text)) return 'Cook gently and avoid stirring hard; fish is ready when opaque and flakes easily. A thermometer should read 63°C/145°F.';
  if (/rice|pulao|biryani|risotto/.test(text)) return 'Check a grain before moving on: it should match the texture described here, not remain chalky in the center.';
  if (/onion|garlic|spice|masala|temper|aromatic/.test(text)) return 'Stay beside the pan and stir often; aromatics and ground spices can scorch quickly.';
  if (/simmer|braise|stew|curry/.test(text)) return 'Keep the liquid at a gentle simmer with small bubbles; lower the heat if it boils vigorously.';
  if (/blend|puree/.test(text)) return 'Let very hot ingredients cool briefly and vent the blender lid safely to prevent steam pressure building.';
  if (/dough|roll|paratha|pizza|flatbread/.test(text)) return 'Use only a light dusting of flour; too much can make the cooked surface dry.';
  if (/rest|serve|finish|fluff/.test(text)) return 'Taste once more before serving and make any final seasoning adjustment gradually.';
  if (/boil|steam/.test(text)) return 'Keep the lid on while steaming; lift it briefly only to check the texture near the end.';
  if (/fry|sear|grill|char/.test(text)) return 'Cook in batches if the pan becomes crowded so the food browns instead of steaming.';
  if (/salad|toss/.test(text) && /dressing|lemon|lime/.test(text)) return 'Add the dressing gradually and stop when the ingredients are lightly coated.';
  if (/mango lassi/.test(recipe.title.toLowerCase())) return 'Blend briefly after adjusting so the drink stays cool and smooth.';
  return undefined;
}

function titleFromInstruction(text: string, index: number): string {
  const s = text.toLowerCase();
  if (/gather|rinse|wash|chop|slice|cut|prepare/.test(s)) return 'Prepare the ingredients';
  if (/marinat/.test(s)) return 'Season and marinate';
  if (/soak|ferment/.test(s)) return 'Prepare the batter';
  if (/blend|puree/.test(s)) return 'Blend until smooth';
  if (/boil|steam|cook the rice/.test(s)) return 'Cook until tender';
  if (/brown|sear|fry|sauté|saute|temper/.test(s)) return 'Sauté until fragrant';
  if (/simmer|braise|poach/.test(s)) return 'Simmer gently';
  if (/bake|grill|roast/.test(s)) return 'Cook until golden';
  if (/serve|finish|taste/.test(s)) return 'Season and serve';
  if (/add|stir|fold|toss|combine/.test(s)) return 'Combine and cook';
  return `Cooking step ${index + 1}`;
}

export function staticRecipeDetails(title: string, ingredients: string[], servings: number, minutes = 30): { ingredientDetails: NonNullable<Recipe['ingredientDetails']>; preparationSteps: PreparationStep[] } {
  const baseServings = Math.max(1, servings);
  const ingredientDetails = ingredients.map(name => {
    const [quantity, unit] = amounts[name] ?? [null, ''];
    return {name, quantity: quantity===null?null:quantity * (baseServings / 2), unit, substitution: null};
  });
  const recipe: Recipe = {id:title,title, cuisine:'', category:'', description:'', image:'', minutes, servings:baseServings, difficulty:'Easy', tags:[], ingredients, steps:[]};
  return {ingredientDetails, preparationSteps: getPreparationSteps(recipe)};
}
